'use strict';

const browserMaintenanceFiles = Object.freeze([
    'js/Card.js',
    'js/GameManager.js',
    'js/pendingActionQueue.js',
    'js/gameTurnPolicy.js',
    'js/gameDicePolicy.js',
    'js/gameCardActivationPolicy.js',
    'js/gameBuildPolicy.js',
    'js/gameCoinTransaction.js',
    'js/gamePendingTransition.js',
    'js/gamePendingResolutionPolicy.js',
    'js/CPU.js',
    'js/Player.js',
    'js/gameSelectionState.js',
    'js/gameSetupState.js',
    'js/gameRuntimeState.js',
    'js/onlineRuntimeState.js',
    'js/onlineSetupState.js',
    'js/RLCPU.js',
    'js/rlModelCatalog.js',
    'js/RLModelPortfolio.js',
    'js/adSlots.js',
    'js/actionContract.js',
    'js/actionUiRegistry.js',
    'js/clientReporting.js',
    'js/clientReportingTransport.js',
    'js/clientEventRuntime.js',
    'js/citySkyline.js',
    'js/clientCheckpoint.js',
    'js/clientStorage.js',
    'js/appShellStorage.js',
    'js/audio.js',
    'js/autoSkipPolicy.js',
    'js/confetti.js',
    'js/cpuActionProposal.js',
    'js/cpuBuildExecution.js',
    'js/cpuBusinessMoves.js',
    'js/cpuDiagnostics.js',
    'js/cpuEvaluation.js',
    'js/cpuEvaluationCache.js',
    'js/cpuLegalMoves.js',
    'js/cpuPendingResolution.js',
    'js/cpuProfile.js',
    'js/cpuSelection.js',
    'js/cpuSimulation.js',
    'js/cpuTuning.js',
    'js/delayedHumanActionPolicy.js',
    'js/cpuSchedulerState.js',
    'js/cpuTurnStrategy.js',
    'js/localActionPolicy.js',
    'js/uiEventDelegation.js',
    'js/uiRuntimeSnapshot.js',
    'js/uiRenderRuntime.js',
    'js/gameEngine.js',
    'js/gameEngineDeterminism.js',
    'js/gameEngineAuthority.js',
    'js/gameEngineClientShadow.js',
    'js/gameEngineRuntimeAdapter.js',
    'js/gameSnapshot.js',
    'js/localSaveRepository.js',
    'js/localSaveRuntime.js',
    'js/localResumePolicy.js',
    'js/localResumePreloadState.js',
    'js/localResumeView.js',
    'js/storedOnlineReconnect.js',
    'js/gameSchemaNegotiation.js',
    'js/gameSchemaCodec.js',
    'js/gameSchemaWire.js',
    'js/recreateRoomPayload.js',
    'js/gameSchemaRecreateWire.js',
    'js/lifecycleNotify.js',
    'js/lifecycleTransport.js',
    'js/localPlayerSettings.js',
    'js/localGameStart.js',
    'js/pageActivationPolicy.js',
    'js/onlinePayload.js',
    'js/onlineRestoreQueueState.js',
    'js/onlineRestoreLifecycleState.js',
    'js/onlineRestoreQueue.js',
    'js/onlineReconnectCleanup.js',
    'js/onlineReconnectRequest.js',
    'js/onlineRestoreAbort.js',
    'js/onlineActionTimeout.js',
    'js/onlineDecodeFailure.js',
    'js/onlineActionApplyFailure.js',
    'js/onlineActionGap.js',
    'js/onlineActionNoGame.js',
    'js/onlineActionCommit.js',
    'js/onlineSocketConnect.js',
    'js/onlineSocketRegistry.js',
    'js/onlineSocketDisconnect.js',
    'js/onlineHostChanged.js',
    'js/onlineRejoinPersistence.js',
    'js/onlinePendingOutboundState.js',
    'js/onlinePendingResend.js',
    'js/onlineRestoreReplay.js',
    'js/onlineRestoreActivation.js',
    'js/onlinePlayerSettings.js',
    'js/onlineLobbyRequestState.js',
    'js/onlineHostlessRestoreState.js',
    'js/onlineRetryPolicy.js',
    'js/onlineReconnectState.js',
    'js/onlineRuntimeFlags.js',
    'js/onlineDiagnosticState.js',
    'js/onlineSchemaTransport.js',
    'js/onlineRestoreRank.js',
    'js/onlineActionSequence.js',
    'js/onlineActionLog.js',
    'js/onlineSessionLifecycle.js',
    'js/onlineStorage.js',
    'js/pwaShell.js',
    'js/savedGameValidation.js',
    'js/storageSettings.js',
    'js/stats.js',
    'js/uiStatsView.js',
    'js/uiBuildMenu.js',
    'js/uiCardDetail.js',
    'js/uiCardOrder.js',
    'js/uiCardSelect.js',
    'js/uiLogDisplay.js',
    'js/uiModalPolicy.js',
    'js/uiModalOpen.js',
    'js/uiModalClose.js',
    'js/uiPlayerDisplay.js',
    'js/uiInputPolicy.js',
    'js/uiNotice.js',
    'js/uiPendingMenu.js',
    'js/uiPendingEffects.js',
    'js/uiTutorialSettings.js',
    'js/uiTutorial.js',
    'js/uiGameStatusView.js',
    'js/uiGameStatusEffects.js',
    'js/uiTabView.js',
    'js/uiTabEffects.js',
    'js/uiDiceChoice.js',
    'js/uiDiceDisplay.js',
    'js/uiTurnAnnouncer.js',
    'js/uiWatchdog.js',
    'js/uiWatchdogMonitor.js',
    'js/uiWatchdogReporting.js',
    'js/clientRuntimeSnapshot.js',
    'js/crashScreen.js',
    'js/crashScreenEffects.js',
    'js/uiWinner.js',
    'js/uiWinnerEffects.js',
]);

const serverMaintenanceFiles = Object.freeze([
    'server.js',
    'scripts/check-static-files.js',
    'scripts/report-action-contract.js',
    'server/actionAcceptance.js',
    'server/canonicalMirrorMetadata.js',
    'server/canonicalMirrorRuntime.js',
    'server/clientErrorReporting.js',
    'server/clientErrorGateway.js',
    'server/gameLifecycleReporting.js',
    'server/gameLifecycleGateway.js',
    'server/reportDelivery.js',
    'server/reportingHttpRoutes.js',
    'server/gameSettings.js',
    'server/runtimeLimits.js',
    'server/gameRuntimeLoader.js',
    'server/gameStartPayload.js',
    'server/gameStartLifecycle.js',
    'server/gameStartAdmission.js',
    'server/gameStartRuntime.js',
    'server/gameStartCoordinator.js',
    'server/hostlessRestoreCandidate.js',
    'server/hostlessRestoreCoordinator.js',
    'server/hostlessRestoreGateway.js',
    'server/hostlessRestoreApproval.js',
    'server/hostlessRestoreDiagnostics.js',
    'server/hostlessRestoreRuntime.js',
    'server/ntfyNotifier.js',
    'server/reconnectIdentity.js',
    'server/restoreAudit.js',
    'server/restoreAuditPayload.js',
    'server/restoreRank.js',
    'server/roomLifecycle.js',
    'server/roomProjection.js',
    'server/roomGcRuntime.js',
    'server/processRuntime.js',
    'server/roomSocketRuntime.js',
    'server/socketConnectionRuntime.js',
    'server/serverDice.js',
    'server/staticAssets.js',
    'server/actionSocketHandler.js',
    'server/actionPayload.js',
    'server/actionValidation.js',
    'server/actionValidationGateway.js',
    'server/canonicalStateStore.js',
    'server/canonicalStateRepository.js',
    'server/clientErrorAuth.js',
    'server/disconnectSocketHandler.js',
    'server/gameSchemaRuntime.js',
    'server/gameSchemaShadow.js',
    'server/gameEngineAuthority.js',
    'server/lobbyAdmission.js',
    'server/lobbySocketHandlers.js',
    'server/mirrorReplay.js',
    'server/rejoinSocketHandler.js',
    'server/recreateSocketHandler.js',
    'server/rejoinPayload.js',
    'server/reportingPolicy.js',
    'server/reportThrottle.js',
    'server/restoreAuditKeyring.js',
    'server/restoreAuditRuntime.js',
    'server/restoreAuditGateway.js',
    'server/restoreSnapshotAttachment.js',
    'server/restoreAuthorityPolicy.js',
    'server/restoreAdmission.js',
    'server/existingRoomRejoin.js',
    'server/existingRoomRestoreRuntime.js',
    'server/newRoomRestoreRuntime.js',
    'server/recreateRoomRuntime.js',
    'server/restoreReplayAdmission.js',
    'server/restorePreparation.js',
    'server/restoreGateway.js',
    'server/restoredRoom.js',
    'server/restoredRoomRuntime.js',
    'server/restoreSanitization.js',
    'server/restoreValidation.js',
    'server/roomValidation.js',
    'server/socketPayload.js',
]);

const maintenanceRules = Object.freeze({
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-duplicate-case': 'error',
    'no-duplicate-imports': 'error',
    'no-undef': 'error',
    'no-unreachable': 'error',
});

module.exports = [
    {
        files: browserMaintenanceFiles,
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                GameActionContract: 'readonly',
                PendingActionQueue: 'readonly',
                GameTurnPolicy: 'readonly',
                GameDicePolicy: 'readonly',
                GameCardActivationPolicy: 'readonly',
                GameBuildPolicy: 'readonly',
                GameCoinTransaction: 'readonly',
                GamePendingTransition: 'readonly',
                GamePendingResolutionPolicy: 'readonly',
                AbortController: 'readonly',
                CARD_CATEGORIES: 'readonly',
                CARD_EFFECTS: 'readonly',
                CARD_IDS: 'readonly',
                CARDS: 'readonly',
                CARD_CATEGORY_GROUPS: 'readonly',
                CARD_EFFECT_METADATA: 'readonly',
                CARD_ID_BY_NAME: 'readonly',
                CARD_NAME_BY_ID: 'readonly',
                alert: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                document: 'readonly',
                escapeHtml: 'readonly',
                fetch: 'readonly',
                getInitialCardStock: 'readonly',
                getCardActivationProfile: 'readonly',
                isOnlineGame: 'readonly',
                isCardInCategoryGroup: 'readonly',
                isReconnectingOnline: 'readonly',
                isRoomHost: 'readonly',
                localStorage: 'readonly',
                navigator: 'readonly',
                performance: 'readonly',
                RLCPU: 'readonly',
                RLModelCatalog: 'readonly',
                console: 'readonly',
                cloneCard: 'readonly',
                createCardByName: 'readonly',
                setInterval: 'readonly',
                showConfirm: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                CPU: 'readonly',
                CPUProfile: 'readonly',                CPUSelection: 'readonly',                CPUDiagnostics: 'readonly',                CPUEvaluationCache: 'readonly',                CPUBusinessMoves: 'readonly',                CPU_EXPERT_PRESETS: 'readonly',                CPU_EXPERT_DEFAULT_OPTIONS: 'readonly',                CPU_EXPERT_PROFILE_TUNINGS: 'readonly',                resolveCpuRuntimeConfig: 'readonly',                resolveExpertProfileTuning: 'readonly',                CPUSimulation: 'readonly',                CPUEvaluation: 'readonly',                CPUBuildExecution: 'readonly',                CPULegalMoves: 'readonly',                CPUPendingResolution: 'readonly',
                console: 'readonly',
                cloneCard: 'readonly',
                createCardByName: 'readonly',
                GAME_PHASES: 'readonly',
                GameManager: 'readonly',
                LANDMARK_NAMES: 'readonly',
                sendAction: 'readonly',
                socket: 'readonly',
                Player: 'readonly',
                module: 'readonly',
                require: 'readonly',
                window: 'readonly',
            },
        },
        linterOptions: {
            reportUnusedDisableDirectives: 'error',
        },
        rules: maintenanceRules,
    },
    {
        files: serverMaintenanceFiles,
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'commonjs',
            globals: {
                Buffer: 'readonly',
                __dirname: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                console: 'readonly',
                global: 'readonly',
                process: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
            },
        },
        linterOptions: {
            reportUnusedDisableDirectives: 'error',
        },
        rules: maintenanceRules,
    },
];
