'use strict';

const browserMaintenanceFiles = Object.freeze([
    'js/Card.js',
    'js/designTheme.js',
    'js/plazaTownLayout.js',
    'js/sharedMarketMount.js',
    'js/plazaField.js',
    'js/uiIncomePreview.js',
    'js/uiIncomePreviewPanel.js',
    'js/uiCardBoard.js',
    'js/cardBoardFeedback.js',
    'js/cardBoardField.js',
    'js/uiPlayerInsights.js',
    'js/dicePresentation.js',
    'js/uiTurnEvents.js',
    'js/uiTurnReceipt.js',
    'js/uiPlazaEvents.js',
    'js/uiPlazaFeedback.js',

    'js/marketSupply.js',
    'js/GameManager.js',
    'js/pendingActionQueue.js',
    'js/gameTurnPolicy.js',
    'js/gameDicePolicy.js',
    'js/gameCardActivationPolicy.js',
    'js/gameBuildPolicy.js',
    'js/gameCoinTransaction.js',
    'js/gamePendingTransition.js',
    'js/gamePendingResolutionPolicy.js',
    'js/CPU.js',
    'js/Player.js',
    'js/gameSelectionState.js',
    'js/gameSetupState.js',
    'js/gameRuntimeState.js',
    'js/onlineRuntimeState.js',
    'js/onlineClientEffects.js',
    'js/onlineDomEffects.js',
    'js/onlineSocketEffects.js',
    'js/onlineComposition.js',
    'js/onlineSetupState.js',
    'js/RLCPU.js',
    'js/rlModelCatalog.js',
    'js/RLModelPortfolio.js',
    'js/adSlots.js',
    'js/actionContract.js',
    'js/actionUiRegistry.js',
    'js/clientReporting.js',
    'js/clientReportingTransport.js',
    'js/appShellClientReportingRuntime.js',
    'js/clientEventRuntime.js',
    'js/citySkyline.js',
    'js/clientCheckpoint.js',
    'js/clientStorage.js',
    'js/appShellStorage.js',
    'js/audio.js',
    'js/autoSkipPolicy.js',
    'js/mainAutoSkipRuntime.js',
    'js/confetti.js',
    'js/cpuActionProposal.js',
    'js/cpuBuildExecution.js',
    'js/cpuBuildProposalCollector.js',
    'js/cpuBuildStrategy.js',
    'js/cpuBuildScoring.js',
    'js/cpuChoiceScoring.js',
    'js/cpuCardEvaluationRuntime.js',
    'js/cpuStateEvaluationRuntime.js',
    'js/cpuBuildPolicyRuntime.js',
    'js/cpuBusinessMoves.js',
    'js/cpuBusinessDecisionRuntime.js',
    'js/cpuDiagnostics.js',
    'js/cpuEvaluation.js',
    'js/cpuEvaluationCache.js',
    'js/cpuLegalMoves.js',
    'js/cpuLookaheadRuntime.js',
    'js/cpuPendingResolution.js',
    'js/cpuPendingDecision.js',
    'js/cpuRollDecision.js',
    'js/cpuProfile.js',
    'js/cpuSelection.js',
    'js/cpuSimulation.js',
    'js/cpuTournament.js',
    'js/cpuTuning.js',
    'js/delayedHumanActionPolicy.js',
    'js/pageActivationRuntime.js',
    'js/cpuSchedulerState.js',
    'js/cpuTurnSchedulerRuntime.js',
    'js/cpuTurnStrategy.js',
    'js/cpuPhaseHandlers.js',
    'js/localActionPolicy.js',
    'js/mainHumanActionRuntime.js',
    'js/uiEventDelegation.js',
    'js/mainUiEventRuntime.js',
    'js/uiRuntimeSnapshot.js',
    'js/uiRenderRuntime.js',
    'js/gameEngine.js',
    'js/gameEngineDeterminism.js',
    'js/gameEngineAuthority.js',
    'js/gameEngineClientShadow.js',
    'js/localGameEngineRuntime.js',
    'js/gameEngineRuntimeAdapter.js',
    'js/gameSnapshot.js',
    'js/localSaveRepository.js',
    'js/localSaveRuntime.js',
    'js/localResumePolicy.js',
    'js/localResumePreloadState.js',
    'js/localResumeView.js',
    'js/localResumeEffects.js',
    'js/localResumePreloadRuntime.js',
    'js/storedOnlineReconnect.js',
    'js/gameSchemaNegotiation.js',
    'js/gameSchemaCodec.js',
    'js/gameSchemaWire.js',
    'js/recreateRoomPayload.js',
    'js/gameSchemaRecreateWire.js',
    'js/lifecycleNotify.js',
    'js/lifecycleRuntime.js',
    'js/lifecycleTransport.js',
    'js/localPlayerSettings.js',
    'js/localGameStart.js',
    'js/localGameStartRuntime.js',
    'js/localGameInitializer.js',
    'js/localGameRestartRuntime.js',
    'js/pageActivationPolicy.js',
    'js/onlineRestoreMetadata.js',
    'js/onlinePayload.js',
    'js/onlineRestoreQueueState.js',
    'js/onlineRestoreLifecycleState.js',
    'js/onlineRestoreQueue.js',
    'js/onlineReconnectCleanup.js',
    'js/onlineReconnectRequest.js',
    'js/onlineRestoreAbort.js',
    'js/onlineActionTimeout.js',
    'js/onlineDecodeFailure.js',
    'js/onlineActionApplyFailure.js',
    'js/onlineActionGap.js',
    'js/onlineActionNoGame.js',
    'js/onlineActionCommit.js',
    'js/onlineSocketConnect.js',
    'js/onlineSocketRegistry.js',
    'js/onlineInboundActionRuntime.js',
    'js/onlineGameEngineRuntime.js',
    'js/onlineLobbyRequestRuntime.js',
    'js/onlineGameInitializer.js',
    'js/onlineLobbyStartRuntime.js',
    'js/onlineLobbySelectionRuntime.js',
    'js/onlineSocketDisconnect.js',
    'js/onlineHostChanged.js',
    'js/onlineEffectAuthority.js',
    'js/onlineRejoinPersistence.js',
    'js/onlineRejoinPreparationRuntime.js',
    'js/onlinePendingOutboundState.js',
    'js/onlinePendingResend.js',
    'js/onlineRestoreReplay.js',
    'js/onlineRestoreRequestRuntime.js',
    'js/onlineAppErrorRuntime.js',
    'js/onlineRestoreActivation.js',
    'js/onlineRejoinActivationRuntime.js',
    'js/onlineRejoinRuntime.js',
    'js/onlinePlayerSettings.js',
    'js/onlineLobbyRequestState.js',
    'js/onlineHostlessRestoreState.js',
    'js/onlineRetryPolicy.js',
    'js/onlineReconnectState.js',
    'js/onlineReconnectRuntime.js',
    'js/onlineRuntimeFlags.js',
    'js/onlineDiagnosticState.js',
    'js/onlineSchemaTransport.js',
    'js/onlineRestoreRank.js',
    'js/onlineActionSequence.js',
    'js/onlineActionLog.js',
    'js/onlineSessionLifecycle.js',
    'js/onlineStorage.js',
    'js/onlineRoomShare.js',
    'js/onlineReadiness.js',
    'js/retryTimer.js',
    'js/socketIoDelivery.js',
    'js/pwaShell.js',
    'js/appShellStartupRuntime.js',
    'js/appDiagnostics.js',
    'js/appBackup.js',
    'js/gameSetupPresets.js',
    'js/roomQrCode.js',
    'js/undoPreview.js',
    'js/uiTurnPrivacy.js',
    'js/snapshotInventoryValidation.js',
    'js/savedGameValidation.js',
    'js/storageSettings.js',
    'js/stats.js',
    'js/uiStatsView.js',
    'js/uiBuildMenu.js',
    'js/uiCardDetail.js',
    'js/uiCardOrder.js',
    'js/uiCardSelect.js',
    'js/uiCardSelectEffects.js',
    'js/uiLogDisplay.js',
    'js/uiLogHighlightEffects.js',
    'js/uiModalPolicy.js',
    'js/uiModalOpen.js',
    'js/uiModalClose.js',
    'js/uiModalDomEffects.js',
    'js/uiModalRuntime.js',
    'js/uiPlayerDisplay.js',
    'js/uiInputPolicy.js',
    'js/uiNotice.js',
    'js/uiPendingMenu.js',
    'js/uiPendingEffects.js',
    'js/uiTutorialSettings.js',
    'js/uiTutorial.js',
    'js/uiGameStatusView.js',
    'js/uiGameStatusEffects.js',
    'js/uiTabView.js',
    'js/uiTabEffects.js',
    'js/uiCpuTournament.js',
    'js/uiDiceChoice.js',
    'js/uiDiceDisplay.js',
    'js/uiTurnAnnouncer.js',
    'js/uiWatchdog.js',
    'js/uiDomSnapshot.js',
    'js/uiRecoveryEffects.js',
    'js/uiWatchdogAsyncRecovery.js',
    'js/uiWatchdogRecoveryRuntime.js',
    'js/appShellUiLockRuntime.js',
    'js/appShellComposition.js',
    'js/appShellRuntimeEffects.js',
    'js/appShellObservationRuntime.js',
    'js/uiWatchdogMonitor.js',
    'js/uiWatchdogReporting.js',
    'js/uiWatchdogRuntime.js',
    'js/clientRuntimeSnapshot.js',
    'js/crashScreen.js',
    'js/crashScreenEffects.js',
    'js/appShellCrashRuntime.js',
    'js/uiWinner.js',
    'js/uiWinnerEffects.js',
    'js/uiPlayerCount.js',
    'js/uiRangeControl.js',
    'js/uiScreenFocus.js',
    'js/appShell.js',
    'js/main.js',
    'js/online.js',
    'js/storage.js',
    'js/ui.js',
]);

const serverMaintenanceFiles = Object.freeze([
    'server.js',
    'scripts/check-static-files.js',
    'scripts/checkjs-root-runner.js',
    'scripts/report-action-contract.js',
    'server/actionAcceptance.js',
    'server/canonicalMirrorMetadata.js',
    'server/canonicalMirrorRuntime.js',
    'server/clientErrorReporting.js',
    'server/clientErrorGateway.js',
    'server/cspReportGateway.js',
    'server/gameLifecycleReporting.js',
    'server/gameLifecycleGateway.js',
    'server/reportDelivery.js',
    'server/reportingHttpRoutes.js',
    'server/gameSettings.js',
    'server/runtimeLimits.js',
    'server/gameRuntimeLoader.js',
    'server/gameStartPayload.js',
    'server/gameStartLifecycle.js',
    'server/gameStartAdmission.js',
    'server/gameStartRuntime.js',
    'server/gameStartCoordinator.js',
    'server/hostlessRestoreCandidate.js',
    'server/hostlessRestoreCoordinator.js',
    'server/hostlessRestoreGateway.js',
    'server/hostlessRestoreApproval.js',
    'server/hostlessRestoreDiagnostics.js',
    'server/hostlessRestoreRuntime.js',
    'server/ntfyNotifier.js',
    'server/reconnectIdentity.js',
    'server/restoreAudit.js',
    'server/restoreAuditPayload.js',
    'server/restoreRank.js',
    'server/roomLifecycle.js',
    'server/roomProjection.js',
    'server/roomGcRuntime.js',
    'server/processRuntime.js',
    'server/roomSocketRuntime.js',
    'server/socketConnectionRuntime.js',
    'server/serverDice.js',
    'server/staticAssets.js',
    'server/actionSocketHandler.js',
    'server/actionPayload.js',
    'server/actionValidation.js',
    'server/actionValidationGateway.js',
    'server/canonicalStateStore.js',
    'server/canonicalStateRepository.js',
    'server/clientErrorAuth.js',
    'server/disconnectSocketHandler.js',
    'server/gameSchemaRuntime.js',
    'server/gameSchemaShadow.js',
    'server/gameEngineAuthority.js',
    'server/lobbyAdmission.js',
    'server/lobbySocketHandlers.js',
    'server/mirrorReplay.js',
    'server/rejoinSocketHandler.js',
    'server/rejoinAdmission.js',
    'server/onlineRematchRuntime.js',
    'server/recreateSocketHandler.js',
    'server/rejoinPayload.js',
    'server/reportingPolicy.js',
    'server/reportThrottle.js',
    'server/restoreAuditKeyring.js',
    'server/restoreAuditRuntime.js',
    'server/restoreAuditGateway.js',
    'server/restoreSnapshotAttachment.js',
    'server/restoreAuthorityPolicy.js',
    'server/restoreAdmission.js',
    'server/existingRoomRejoin.js',
    'server/existingRoomRestoreRuntime.js',
    'server/newRoomRestoreRuntime.js',
    'server/recreateRoomRuntime.js',
    'server/restoreReplayAdmission.js',
    'server/restorePreparation.js',
    'server/restoreGateway.js',
    'server/restoredRoom.js',
    'server/restoredRoomRuntime.js',
    'server/restoreSanitization.js',
    'server/restoreValidation.js',
    'server/roomValidation.js',
    'server/socketPayload.js',
    'server/socketOriginPolicy.js',
    'server/securityHeaders.js',
]);

const maintenanceRules = Object.freeze({
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-constant-binary-expression': 'error',
    'no-duplicate-case': 'error',
    'no-dupe-args': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-imports': 'error',
    'no-eval': 'error',
    'no-implied-eval': 'error',
    'no-async-promise-executor': 'error',
    'no-promise-executor-return': 'error',
    'no-throw-literal': 'error',
    'no-obj-calls': 'error',
    'no-loss-of-precision': 'error',
    'no-prototype-builtins': 'error',
    'no-new-func': 'error',
    'no-undef': 'error',
    'no-sparse-arrays': 'error',
    'no-script-url': 'error',
    'no-unreachable': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unsafe-finally': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable-loop': 'error',
    'no-fallthrough': 'error',
    'require-atomic-updates': 'error',
    'valid-typeof': 'error',
});

const appShellCompositionGlobals = Object.freeze(Object.fromEntries([
    'AppShellClientReportingRuntime', 'AppShellComposition', 'AppShellCrashRuntime',
    'AppShellObservationRuntime', 'AppShellRuntimeEffects', 'AppShellStartupRuntime',
    'AppShellStorage', 'AppShellUiLockRuntime', 'ActionUiRegistry', 'ClientCheckpoint',
    'ClientEventRuntime', 'ClientReporting', 'ClientReportingTransport', 'ClientRuntimeSnapshot',
    'CrashScreen', 'CrashScreenEffects', 'GameRuntimeState', 'GameSetupState',
    'LifecycleNotify', 'LifecycleRuntime', 'LifecycleTransport', 'OnlineRetryPolicy',
    'OnlineRuntimeState', 'PwaShell', 'RetryTimer', 'UiDomSnapshot', 'UiRecoveryEffects',
    'UiScreenFocus', 'UiTabEffects', 'UiTabView', 'UiWatchdog', 'UiWatchdogAsyncRecovery',
    'UiWatchdogMonitor', 'UiWatchdogRecoveryRuntime', 'UiWatchdogReporting', 'UiWatchdogRuntime',
    'cancelCpuSchedule', 'cardFilter', 'closeAccessibleModal', 'closeConfirmModal',
    'cpuSchedulerStateController', 'cpuTurnScheduler', 'drawCitySkyline', 'enabledLandmarks',
    'getOnlineActionFlightState', 'loadSettings', 'onlineActionInFlight', 'onlineActionInFlightAt',
    'preloadLocalRlModelsInBackground', 'preloadOnlineRlModelsInBackground', 'render',
    'renderBuildMenu', 'renderOnlinePlayerSettings', 'resumeGame', 'scheduleCPU',
    'SHOP_STOCK', 'resetAccessibleModalRuntimeState', 'updateGameActivityStatus',
    'updateGameActivityWatchdogStatus', 'updateResumeButton', '_handleOnlineActionTimeout',
    '_isOnlineFlowActive', 'activeModalId', 'lastModalFocus', 'modalInertRestore',
].map(name => [name, 'readonly'])));
const mainCompositionGlobals = Object.freeze(Object.fromEntries([
    'AppBackup', 'AppDiagnostics', 'AutoSkipPolicy', 'CitySkyline', 'ClientStorage',
    'CpuPhaseHandlers', 'CpuSchedulerState', 'CpuTournament', 'CpuTurnSchedulerRuntime',
    'CpuTurnStrategy', 'DelayedHumanActionPolicy', 'GameEngine', 'GameEngineClientShadow',
    'GameEngineDeterminism', 'GameEngineRuntimeAdapter', 'GameSelectionState', 'GameSetupPresets',
    'LocalActionPolicy', 'LocalGameEngineRuntime', 'LocalGameInitializer', 'LocalGameRestartRuntime',
    'LocalGameStart', 'LocalGameStartRuntime', 'LocalPlayerSettings', 'MainAutoSkipRuntime',
    'MainHumanActionRuntime', 'MainUiEventRuntime', 'PageActivationPolicy', 'PageActivationRuntime',
    'RoomQrCode', 'UiCpuTournament', 'UiDiceDisplay', 'UiEventDelegation', 'UiGameStatusView',
    'UiPlayerCount', 'UiPlayerDisplay', 'PlazaField', 'UiRangeControl', 'UiScreenFocus', 'UiTabView', 'UiWinner',
    '_readOnlineActionLog', 'getEnabledCardSelection', 'getEnabledLandmarkSelection',
    'getLocalSaveRepository', 'isOnlineReconnectInputBlocked', 'isValidSavedGameState',
    'readOnlineSession', 'recordFlowTrace', 'replaceEnabledCardSelection',
    'replaceEnabledLandmarkSelection', 'replaceMarketRuleSelection', 'resetFullLog',
    'resetOnlineState', 'resetStatsRecorded', 'resumeOnlineReconnectAfterPageActivation',
    'saveSettings', 'saveUndoState', 'syncCardSelectStateFromRuntime', 'switchOnlineTab',
    'switchTab', 'updateGameSelectionSummary', 'refreshPwaUpdateState', 'clearOnlineSessionStorage',
].map(name => [name, 'readonly'])));
const mainEnvironmentGlobals = Object.freeze(Object.fromEntries([
    'Blob', 'GAME_ACTIONS', 'GameRuntimeState', 'GameSetupState', 'GameSnapshot',
    'LOG_TYPES', 'OnlineRuntimeState', 'RLModelPortfolio', 'UiGameStatusEffects',
    'UiScreenFocus', 'UiTabView', 'UiTutorialSettings', 'URL', 'assignShopStockSnapshot',
    'getOnlineActionFlightState', 'getShopStockCount', 'initMainView',
    'markClientFlowCheckpoint', 'notifyGameLifecycleStart', 'onlineActionInFlight',
    'onlineActionInFlightAt', 'playSound', 'render', 'reportClientError',
    'resetFreezeWatchdogAfterPageActivation', 'resetGameLifecycleForRestart',
    'resetUiLocksForGameReset', 'rollRandomDie', 'setShopStockCount', 'showNotice',
    'stopConfetti', 'unlockUiForHumanTurn', 'updateResumeButton', 'winSoundPlayed',
    'resolveLiveCpuOptions',
].map(name => [name, 'readonly'])));
const onlineEnvironmentGlobals = Object.freeze(Object.fromEntries([
    'OnlineSetupState',
    'OnlineLobbyRequestState',
    'OnlineSocketRegistry',
    'invalidateCpuScheduleChain',
    'notifyGameLifecycleStart',
    'render',
    'resetUiLocksForGameReset',
    'scheduleCPU',
    'showNotice',
    'updateResumeButton',
    'OnlineComposition',
    'OnlineClientEffects',
    'ClientStorage',
    'OnlineDomEffects',
    'GameRuntimeState',
    'OnlinePayload',
    'OnlineRuntimeState',
    'OnlineSocketEffects',
    'OnlineRoomShare',
    'OnlineReadiness',
    'RoomQrCode',
    'switchTab',
    'switchOnlineTab',
    'GameSelectionState',
    'replaceEnabledCardSelection',
    'replaceEnabledLandmarkSelection',
    'replaceMarketRuleSelection',
    'updateGameSelectionSummary',
    'createCpuPlayer',
    'OnlinePlayerSettings',
    'RLModelPortfolio',
    'OnlineSchemaTransport',
    'OnlineRuntimeFlags',
    'GameSchemaNegotiation',
    'GameSchemaWire',
    'GameSchemaRecreateWire',
    'UiPlayerCount',
    'OnlineHostlessRestoreState',
    'OnlineRestoreQueueState',
    'OnlineRestoreRequestRuntime',
    'OnlineAppErrorRuntime',
    'OnlineDiagnosticState',
    'OnlineActionSequence',
    'OnlineRestoreLifecycleState',
    'OnlinePendingOutboundState',
    'OnlineRetryPolicy',
    'OnlineReconnectRuntime',
    'OnlineReconnectState',
    'createOnlineStorageFacade',
    'GAME_ACTION_REGISTRY',
    'readOnlineSession',
    'OnlineReconnectRequest',
    'OnlineEffectAuthority',
    'OnlineActionTimeout',
    'OnlineDecodeFailure',
    'OnlineActionApplyFailure',
    'OnlineActionGap',
    'OnlineActionNoGame',
    'OnlineActionCommit',
    'OnlineSocketConnect',
    'OnlineSocketDisconnect',
    'OnlineHostChanged',
    'LOG_TYPES',
    'OnlineRejoinPersistence',
    'OnlinePendingResend',
    'OnlineRestoreReplay',
    'OnlineRestoreActivation',
    'OnlineSessionLifecycle',
    'OnlineActionLog',
    'OnlineRestoreRank',
    'OnlineRestoreAbort',
    'OnlineRestoreQueue',
    'OnlineInboundActionRuntime',
    'markClientFlowCheckpoint',
    'location',
    'reportClientError',
    'io',
    'OnlineLobbyStartRuntime',
    'OnlineLobbySelectionRuntime',
    'UiScreenFocus',
    'isCurrentHumanUiTurn',
    'GameSetupState',
    'winSoundPlayed',
    'UiWinner',
    'OnlineRejoinPreparationRuntime',
    'OnlineRejoinActivationRuntime',
    'OnlineRejoinRuntime',
    'OnlineReconnectCleanup',
    'refreshPwaUpdateState',
    'OnlineLobbyRequestRuntime',
    'OnlineGameInitializer',
    'cancelAutoSkip',
    'cancelDelayedHumanAction',
    'resetFullLog',
    'resetStatsRecorded',
    'setShopStockCount',
    'GameEngineRuntimeAdapter',
    'assignShopStockSnapshot',
    'GameEngine',
    'restoreUndoSnapshot',
    'OnlineGameEngineRuntime',
    'GameEngineClientShadow',
    'crypto',
    'GameSnapshot',
    'SHOP_STOCK',
].map(name => [name, 'readonly'])));
const storageEnvironmentGlobals = Object.freeze(Object.assign(
    {},
    appShellCompositionGlobals,
    mainCompositionGlobals,
    mainEnvironmentGlobals,
    onlineEnvironmentGlobals,
    Object.fromEntries([
        'LocalSaveRepository', 'LocalResumePolicy', 'LocalResumePreloadState',
        'LocalResumeEffects', 'LocalResumeView', 'LocalResumePreloadRuntime', 'SavedGameValidation',
        'SnapshotInventoryValidation', 'StorageSettings', 'StoredOnlineReconnect',
        'UndoPreview', 'isPlainObject', 'ONLINE_SESSION_STORAGE_KEY',
        'ONLINE_ROOM_STORAGE_KEY_SEPARATOR', 'ONLINE_STORAGE_KEYS',
        'ONLINE_RESTORE_ROOM_INDEX_KEY', '_clearOnlineRestoreBundle',
        '_clearRejoinRetry', '_emitOnlineRejoinRequest', 'initSocket',
        'myPlayerName', 'myRoomId', 'myOriginalPlayerIndex', 'myPlayerIndex',
        'reconnectToken', 'setSoundVolume', 'setSoundEffectEnabled',
        'syncTutorialControls', 'normalizeLocalPlayerName', 'formatCpuSpeedLabel',
        'runLocalOrSendOnline', 'getEnabledCardSelection', 'getEnabledLandmarkSelection',
        'setOnlineReconnectLegacyFlag', 'LocalSaveRuntime', 'onlineDomEffects',
        'renderPlayerSettings',
    ].map(name => [name, 'readonly']))
));
const uiEnvironmentGlobals = Object.freeze(Object.assign(
    {},
    storageEnvironmentGlobals,
    Object.fromEntries([
        'UiLogDisplay', 'UiLogHighlightEffects', 'UiPendingEffects', 'UiDiceChoice', 'UiDiceDisplay', 'UiBuildMenu',
        'safeStorageSet', 'safeStorageRemove', 'UiTutorial', 'ensureCurrentScreenFocus',
        'showCrashScreen', 'UiRenderRuntime', 'updateGameActivityStatus', 'renderAdSlot',
        'UiWinnerEffects', 'recordGameStats', 'notifyGameLifecycleFinish',
        'markOnlineGameFinished', 'startConfetti', 'File', 'URL', 'updateDiceDisplay',
        'showCoinAnimation', 'syncUiInteractabilityAfterRender', 'schedulePostBuildUiStabilizer',
        'checkAutoSkip', 'saveGameState', 'getOnlineActionFlightState', 'onlineActionInFlight',
        'onlineActionInFlightAt', 'UiInputPolicy', 'UiPendingMenu', 'UiCardDetail',
        'CARD_EFFECT_DESCRIPTIONS', 'checkOnlineReadiness', 'renderStats', 'UiCardSelect',
        'UiCardSelectEffects', 'UiModalPolicy', 'UiRuntimeSnapshot', 'UiCardOrder',
        'UiModalDomEffects', 'UiModalRuntime', 'UiModalClose', 'UiModalOpen',
        'UiTurnPrivacy', 'UiTurnAnnouncer',
        'beginOnlineCardSelection', 'saveOnlineCardSelection',
    ].map(name => [name, 'readonly']))
));

module.exports = [
    {
        files: browserMaintenanceFiles,
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                GameActionContract: 'readonly',
                PendingActionQueue: 'readonly',
                GameTurnPolicy: 'readonly',
                GameDicePolicy: 'readonly',
                GameCardActivationPolicy: 'readonly',
                GameBuildPolicy: 'readonly',
                GameCoinTransaction: 'readonly',
                GamePendingTransition: 'readonly',
                GamePendingResolutionPolicy: 'readonly',
                AbortController: 'readonly',
                CARD_CATEGORIES: 'readonly',
                CARD_EFFECTS: 'readonly',
                CARD_IDS: 'readonly',
                CARDS: 'readonly',
                CARD_CATEGORY_GROUPS: 'readonly',
                CARD_EFFECT_METADATA: 'readonly',
                CARD_ID_BY_NAME: 'readonly',
                CARD_NAME_BY_ID: 'readonly',
                alert: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                document: 'readonly',
                escapeHtml: 'readonly',
                fetch: 'readonly',
                getInitialCardStock: 'readonly',
                MarketSupply: 'readonly',
                decrementMarketShopStock: 'readonly',
                getCardActivationProfile: 'readonly',
                isOnlineGame: 'readonly',
                isCardInCategoryGroup: 'readonly',
                isReconnectingOnline: 'readonly',
                isRoomHost: 'readonly',
                localStorage: 'readonly',
                navigator: 'readonly',
                performance: 'readonly',
                RLCPU: 'readonly',
                RLModelCatalog: 'readonly',
                console: 'readonly',
                cloneCard: 'readonly',
                createCardByName: 'readonly',
                setInterval: 'readonly',
                showConfirm: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                CPU: 'readonly',
                CPUActionProposal: 'readonly',
                CPUProfile: 'readonly',                CPUSelection: 'readonly',                CPUDiagnostics: 'readonly',                CPUEvaluationCache: 'readonly',                CPUBusinessMoves: 'readonly',                CPUBusinessDecisionRuntime: 'readonly',                CPU_EXPERT_PRESETS: 'readonly',                CPU_EXPERT_DEFAULT_OPTIONS: 'readonly',                CPU_EXPERT_PROFILE_TUNINGS: 'readonly',                resolveCpuRuntimeConfig: 'readonly',                resolveExpertProfileTuning: 'readonly',                CPUSimulation: 'readonly',                CPUEvaluation: 'readonly',                CPUBuildExecution: 'readonly',                CPUBuildStrategy: 'readonly',                CPUBuildScoring: 'readonly',                CPUChoiceScoring: 'readonly',                CPUCardEvaluationRuntime: 'readonly',                CPUStateEvaluationRuntime: 'readonly',                CPUBuildPolicyRuntime: 'readonly',                CPULegalMoves: 'readonly',                CPULookaheadRuntime: 'readonly',                CPUPendingResolution: 'readonly',                CPUPendingDecision: 'readonly',                CPURollDecision: 'readonly',
                console: 'readonly',
                cloneCard: 'readonly',
                createCardByName: 'readonly',
                GAME_PHASES: 'readonly',
                GameManager: 'readonly',
                LANDMARK_NAMES: 'readonly',
                sendAction: 'readonly',
                socket: 'readonly',
                Player: 'readonly',
                module: 'readonly',
                require: 'readonly',
                window: 'readonly',
            },
        },
        linterOptions: {
            reportUnusedDisableDirectives: 'error',
        },
        rules: maintenanceRules,
    },
    {
        files: serverMaintenanceFiles,
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'commonjs',
            globals: {
                Buffer: 'readonly',
                __dirname: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                console: 'readonly',
                global: 'readonly',
                process: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
            },
        },
        linterOptions: {
            reportUnusedDisableDirectives: 'error',
        },
        rules: maintenanceRules,
    },
    {
        files: ['js/appShell.js'],
        languageOptions: { globals: appShellCompositionGlobals },
        rules: maintenanceRules,
    },
    {
        files: ['js/main.js'],
        languageOptions: { globals: Object.assign({}, mainCompositionGlobals, mainEnvironmentGlobals) },
        rules: maintenanceRules,
    },
    {
        files: ['js/online.js'],
        languageOptions: { globals: onlineEnvironmentGlobals },
        rules: maintenanceRules,
    },
    {
        files: ['js/storage.js'],
        languageOptions: { globals: storageEnvironmentGlobals },
        rules: maintenanceRules,
    },
    {
        files: ['js/ui.js'],
        languageOptions: { globals: uiEnvironmentGlobals },
        rules: maintenanceRules,
    },
];
