'use strict';

const browserMaintenanceFiles = Object.freeze([
    'js/Card.js',
    'js/GameManager.js',
    'js/CPU.js',
    'js/Player.js',
    'js/RLCPU.js',
    'js/RLModelPortfolio.js',
    'js/adSlots.js',
    'js/actionContract.js',
    'js/actionUiRegistry.js',
    'js/clientReporting.js',
    'js/clientStorage.js',
    'js/appShellStorage.js',
    'js/audio.js',
    'js/confetti.js',
    'js/cpuActionProposal.js',
    'js/cpuBuildExecution.js',
    'js/cpuBusinessMoves.js',
    'js/cpuDiagnostics.js',
    'js/cpuEvaluation.js',
    'js/cpuEvaluationCache.js',
    'js/cpuLegalMoves.js',
    'js/cpuPendingResolution.js',
    'js/cpuProfile.js',
    'js/cpuSimulation.js',
    'js/cpuTuning.js',
    'js/gameEngine.js',
    'js/gameSnapshot.js',
    'js/localSaveRepository.js',
    'js/gameSchemaNegotiation.js',
    'js/gameSchemaCodec.js',
    'js/gameSchemaWire.js',
    'js/recreateRoomPayload.js',
    'js/gameSchemaRecreateWire.js',
    'js/lifecycleNotify.js',
    'js/localPlayerSettings.js',
    'js/onlinePayload.js',
    'js/onlineRestoreQueue.js',
    'js/onlineReconnectCleanup.js',
    'js/onlinePlayerSettings.js',
    'js/onlineRetryPolicy.js',
    'js/onlineReconnectState.js',
    'js/onlineRestoreRank.js',
    'js/onlineStorage.js',
    'js/pwaShell.js',
    'js/savedGameValidation.js',
    'js/storageSettings.js',
    'js/stats.js',
    'js/uiBuildMenu.js',
    'js/uiCardDetail.js',
    'js/uiCardOrder.js',
    'js/uiCardSelect.js',
    'js/uiLogDisplay.js',
    'js/uiModalPolicy.js',
    'js/uiPlayerDisplay.js',
    'js/uiNotice.js',
    'js/uiPendingMenu.js',
    'js/uiTutorial.js',
    'js/uiGameStatusView.js',
    'js/uiTabView.js',
    'js/uiDiceChoice.js',
    'js/uiWatchdog.js',
    'js/uiWinner.js',
]);

const serverMaintenanceFiles = Object.freeze([
    'server.js',
    'scripts/report-action-contract.js',
    'server/actionAcceptance.js',
    'server/canonicalMirrorMetadata.js',
    'server/clientErrorReporting.js',
    'server/gameLifecycleReporting.js',
    'server/gameSettings.js',
    'server/gameStartPayload.js',
    'server/hostlessRestoreCandidate.js',
    'server/hostlessRestoreCoordinator.js',
    'server/hostlessRestoreGateway.js',
    'server/hostlessRestoreRuntime.js',
    'server/ntfyNotifier.js',
    'server/reconnectIdentity.js',
    'server/restoreAudit.js',
    'server/restoreRank.js',
    'server/roomLifecycle.js',
    'server/serverDice.js',
    'server/staticAssets.js',
    'server/actionSocketHandler.js',
    'server/actionPayload.js',
    'server/actionValidation.js',
    'server/canonicalStateStore.js',
    'server/clientErrorAuth.js',
    'server/disconnectSocketHandler.js',
    'server/gameSchemaRuntime.js',
    'server/gameSchemaShadow.js',
    'server/gameEngineAuthority.js',
    'server/lobbySocketHandlers.js',
    'server/mirrorReplay.js',
    'server/rejoinSocketHandler.js',
    'server/recreateSocketHandler.js',
    'server/rejoinPayload.js',
    'server/reportingPolicy.js',
    'server/reportThrottle.js',
    'server/restoreAuditKeyring.js',
    'server/restoreAuthorityPolicy.js',
    'server/restoreGateway.js',
    'server/restoreSanitization.js',
    'server/restoreValidation.js',
    'server/roomValidation.js',
    'server/socketPayload.js',
]);

const maintenanceRules = Object.freeze({
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-duplicate-case': 'error',
    'no-duplicate-imports': 'error',
    'no-undef': 'error',
    'no-unreachable': 'error',
});

module.exports = [
    {
        files: browserMaintenanceFiles,
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                GameActionContract: 'readonly',
                AbortController: 'readonly',
                CARD_CATEGORIES: 'readonly',
                CARD_EFFECTS: 'readonly',
                CARD_IDS: 'readonly',
                CARDS: 'readonly',
                CARD_CATEGORY_GROUPS: 'readonly',
                CARD_EFFECT_METADATA: 'readonly',
                CARD_ID_BY_NAME: 'readonly',
                CARD_NAME_BY_ID: 'readonly',
                alert: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                document: 'readonly',
                escapeHtml: 'readonly',
                fetch: 'readonly',
                getInitialCardStock: 'readonly',
                getCardActivationProfile: 'readonly',
                isOnlineGame: 'readonly',
                isCardInCategoryGroup: 'readonly',
                isReconnectingOnline: 'readonly',
                isRoomHost: 'readonly',
                localStorage: 'readonly',
                navigator: 'readonly',
                performance: 'readonly',
                RLCPU: 'readonly',
                console: 'readonly',
                cloneCard: 'readonly',
                createCardByName: 'readonly',
                setInterval: 'readonly',
                showConfirm: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                CPU: 'readonly',
                CPUProfile: 'readonly',                CPUDiagnostics: 'readonly',                CPUEvaluationCache: 'readonly',                CPUBusinessMoves: 'readonly',                CPU_EXPERT_PRESETS: 'readonly',                CPU_EXPERT_DEFAULT_OPTIONS: 'readonly',                CPU_EXPERT_PROFILE_TUNINGS: 'readonly',                CPUSimulation: 'readonly',                CPUEvaluation: 'readonly',                CPUBuildExecution: 'readonly',                CPULegalMoves: 'readonly',                CPUPendingResolution: 'readonly',
                console: 'readonly',
                cloneCard: 'readonly',
                createCardByName: 'readonly',
                GAME_PHASES: 'readonly',
                GameManager: 'readonly',
                LANDMARK_NAMES: 'readonly',
                sendAction: 'readonly',
                socket: 'readonly',
                Player: 'readonly',
                module: 'readonly',
                require: 'readonly',
                window: 'readonly',
            },
        },
        linterOptions: {
            reportUnusedDisableDirectives: 'error',
        },
        rules: maintenanceRules,
    },
    {
        files: serverMaintenanceFiles,
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'commonjs',
            globals: {
                Buffer: 'readonly',
                __dirname: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                console: 'readonly',
                global: 'readonly',
                process: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
            },
        },
        linterOptions: {
            reportUnusedDisableDirectives: 'error',
        },
        rules: maintenanceRules,
    },
];
