const { resolveTestConcurrency, runTestFiles } = require('./helpers/test-process-runner');
const fs = require('fs');
const path = require('path');

const TEST_GROUPS = {
    unit: [
        'gamemanager.test.js',
        'pending-action-queue.test.js',
        'game-turn-policy.test.js',
        'game-dice-policy.test.js',
        'game-card-activation-policy.test.js',
        'game-build-policy.test.js',
        'game-coin-transaction.test.js',
        'game-pending-transition.test.js',
        'game-pending-resolution-policy.test.js',
        'action-contract.test.js',
        'action-ui-registry.test.js',
        'action-contract-report.test.js',
        'card-contract.test.js',
        'server.test.js',
        'server-dice.test.js',
        'canonical-mirror-metadata.test.js',
        'canonical-mirror-runtime.test.js',
        'canonical-state-store.test.js',
        'canonical-state-repository.test.js',
        'action-acceptance.test.js',
        'action-payload.test.js',
        'action-validation.test.js',
        'action-validation-gateway.test.js',
        'game-lifecycle-reporting.test.js',
        'game-lifecycle-gateway.test.js',
        'report-delivery.test.js',
        'reporting-http-routes.test.js',
        'game-settings.test.js',
        'server-runtime-limits.test.js',
        'game-runtime-loader.test.js',
        'game-start-payload.test.js',
        'game-start-lifecycle.test.js',
        'game-start-admission.test.js',
        'game-start-coordinator.test.js',
        'room-validation.test.js',
        'room-lifecycle.test.js',
        'room-projection.test.js',
        'room-gc-runtime.test.js',
        'process-runtime.test.js',
        'room-socket-runtime.test.js',
        'socket-connection-runtime.test.js',
        'lobby-admission.test.js',
        'lobby-socket-handlers.test.js',
        'reconnect-identity.test.js',
        'rejoin-payload.test.js',
        'rejoin-socket-handler.test.js',
        'action-socket-handler.test.js',
        'recreate-socket-handler.test.js',
        'recreate-room-runtime.test.js',
        'restore-admission.test.js',
        'existing-room-rejoin.test.js',
        'restore-replay-admission.test.js',
        'restore-preparation.test.js',
        'restore-gateway.test.js',
        'restored-room.test.js',
        'restored-room-runtime.test.js',
        'disconnect-socket-handler.test.js',
        'restore-sanitization.test.js',
        'restore-validation.test.js',
        'restore-audit-payload.test.js',
        'restore-audit-keyring.test.js',
        'restore-audit-runtime.test.js',
        'restore-audit-gateway.test.js',
        'restore-snapshot-attachment.test.js',
        'restore-authority-policy.test.js',
        'hostless-restore-candidate.test.js',
        'hostless-restore-coordinator.test.js',
        'hostless-restore-gateway.test.js',
        'hostless-restore-approval.test.js',
        'hostless-restore-diagnostics.test.js',
        'hostless-restore-runtime.test.js',
        'static-assets.test.js',
        'socket-payload.test.js',
        'socket-e2e-helper.test.js',
        'game-engine.test.js',
        'game-snapshot.test.js',
        'local-save-repository.test.js',
        'local-save-runtime.test.js',
        'game-schema-negotiation.test.js',
        'game-schema-codec.test.js',
        'game-schema-wire.test.js',
        'recreate-room-payload.test.js',
        'game-schema-recreate-wire.test.js',
        'game-schema-runtime.test.js',
        'game-schema-shadow.test.js',
        'game-engine-authority.test.js',
        'game-engine-client-shadow.test.js',
        'game-engine-determinism.test.js',
        'game-engine-local-shadow.test.js',
        'game-engine-runtime-adapter.test.js',
        'game-schema-shadow-parity.test.js',
        'snapshot-contract.test.js',
        'client-checkpoint.test.js',
        'client-error-reporting.test.js',
        'client-error-gateway.test.js',
        'client-reporting-transport.test.js',
        'app-shell-client-reporting-runtime.test.js',
        'client-event-runtime.test.js',
        'reporting-policy.test.js',
        'report-throttle.test.js',
        'cpu.test.js',
        'cpu-profile.test.js',
        'cpu-selection.test.js',
        'cpu-evaluation.test.js',
        'cpu-legal-moves.test.js',
        'cpu-business-moves.test.js',
        'cpu-action-proposal.test.js',
        'cpu-build-execution.test.js',
        'cpu-simulation.test.js',
        'cpu-decision-snapshot.test.js',
        'cpu-decision-baseline.test.js',
        'online-setup-state.test.js',
        'online-player-settings.test.js',
        'online-lobby-request-state.test.js',
        'online-hostless-restore-state.test.js',
        'online-storage.test.js',
        'online.test.js',
        'online-payload.test.js',
        'online-restore-queue.test.js',
        'online-restore-queue-state.test.js',
        'online-restore-lifecycle-state.test.js',
        'online-reconnect-cleanup.test.js',
        'online-reconnect-request.test.js',
        'online-restore-abort.test.js',
        'online-action-timeout.test.js',
        'online-decode-failure.test.js',
        'online-action-apply-failure.test.js',
        'online-action-gap.test.js',
        'online-action-no-game.test.js',
        'online-action-commit.test.js',
        'online-socket-connect.test.js',
        'online-socket-registry.test.js',
        'online-socket-disconnect.test.js',
        'online-host-changed.test.js',
        'online-rejoin-persistence.test.js',
        'online-pending-outbound-state.test.js',
        'online-pending-resend.test.js',
        'online-restore-replay.test.js',
        'online-restore-activation.test.js',
        'online-restore-rank.test.js',
        'online-action-sequence.test.js',
        'online-action-log.test.js',
        'online-session-lifecycle.test.js',
        'online-reconnect-state.test.js',
        'online-runtime-state.test.js',
        'online-client-effects.test.js',
        'online-dom-effects.test.js',
        'online-socket-effects.test.js',
        'online-runtime-flags.test.js',
        'online-diagnostic-state.test.js',
        'online-retry-policy.test.js',
        'online-integration.test.js',
        'online-delivery-smoke.test.js',
        'online-delivery-handshake.test.js',
        'saved-game-validation.test.js',
        'storage-settings.test.js',
        'local-resume-policy.test.js',
        'local-resume-preload-state.test.js',
        'local-resume-view.test.js',
        'stored-online-reconnect.test.js',
        'storage.test.js',
        'game-setup-state.test.js',
        'game-runtime-state.test.js',
        'local-player-settings.test.js',
        'local-game-start.test.js',
        'local-game-start-runtime.test.js',
        'local-game-initializer.test.js',
        'auto-skip-policy.test.js',
        'page-activation-policy.test.js',
        'delayed-human-action-policy.test.js',
        'cpu-scheduler-state.test.js',
        'cpu-turn-strategy.test.js',
        'local-action-policy.test.js',
        'ui-event-delegation.test.js',
        'city-skyline.test.js',
    'main.test.js',
        'client-reporting.test.js',
        'client-storage.test.js',
        'app-shell-storage.test.js',
        'app-shell-runtime-effects.test.js',
        'app-shell-observation-runtime.test.js',
        'sw.test.js',
        'confetti.test.js',
        'stats.test.js',
        'ui-stats-view.test.js',
        'ui-log-display.test.js',
        'ui-card-order.test.js',
        'ui-card-detail.test.js',
        'ui-player-display.test.js',
        'ui-input-policy.test.js',
        'game-selection-state.test.js',
        'ui-card-select.test.js',
        'ui-tutorial-settings.test.js',
        'ui-tutorial.test.js',
        'ui-dice-choice.test.js',
        'ui-dice-display.test.js',
        'ui-turn-announcer.test.js',
        'ui-modal-open.test.js',
        'ui-modal-close.test.js',
        'ui-modal-policy.test.js',
        'ui-game-status-view.test.js',
        'ui-game-status-effects.test.js',
        'ui-tab-view.test.js',
        'ui-tab-effects.test.js',
        'ui-runtime-snapshot.test.js',
        'ui-render-runtime.test.js',
        'ui-pending-menu.test.js',
        'ui-pending-effects.test.js',
        'ui-watchdog.test.js',
        'ui-dom-snapshot.test.js',
        'ui-recovery-effects.test.js',
        'ui-watchdog-async-recovery.test.js',
        'ui-watchdog-recovery-runtime.test.js',
        'app-shell-ui-lock-runtime.test.js',
        'ui-watchdog-monitor.test.js',
        'ui-watchdog-reporting.test.js',
        'ui-watchdog-runtime.test.js',
        'client-runtime-snapshot.test.js',
        'crash-screen.test.js',
        'crash-screen-effects.test.js',
        'app-shell-crash-runtime.test.js',
        'ui-winner.test.js',
        'ui-winner-effects.test.js',
        'lifecycle-notify.test.js',
        'lifecycle-runtime.test.js',
        'lifecycle-transport.test.js',
        'pwa-shell.test.js',
        'app-shell-startup-runtime.test.js',
        'ui.test.js',
        'integration.test.js',
        'rlcpu.test.js',
        'rl-model-portfolio.test.js',
        'validate-rl-registry.test.js',
        'report-rl-registry.test.js',
        'audit-rl-portfolio.test.js',
        'plan-rl-next-actions.test.js',
        'review-rl-adoptions.test.js',
        'refresh-rl-ops-reports.test.js',
        'report-rl-diversity.test.js',
        'review-rl-multiplayer-topk.test.js',
        'review-rl-multiplayer-experiment-set.test.js',
        'rl-train.test.js',
        'rl-match-trace.test.js',
        'compare-rl-match-trace.test.js',
        'js-cpu-oracle.test.js',
        'resolve-rl-model-path.test.js',
        'eval-expert-v2-benchmark-pack.test.js',
        'eval-expert-v2-multiseed.test.js',
        'eval-expert-vs-strong.test.js',
        'eval-expert-vs-normal.test.js',
        'eval-expert-vs-weak.test.js',
        'diagnose-expert-losses.test.js',
        'summarize-expert-losses-json.test.js',
        'diagnose-expert-v2-branches.test.js',
        'search-expert-top-tier.test.js',
        'eval-rl-vs-js.test.js',
        'eval-rl-models.test.js',
        'diagnose-rl-build-pass.test.js',
        'diagnose-rl-landmark-race.test.js',
        'render-rl-registry-evals.test.js',
        'update-rl-registry-from-eval.test.js',
        'eval-rl-business-scenario.test.js',
        'eval-rl-special-scenarios.test.js',
        'summarize-rl-metrics.test.js',
        'cli-args.test.js',
        'test-utils.test.js',
        'test-process-runner.test.js',
        'check-static-files.test.js',
        'batch-test-script.test.js',
        'maintenance-lint-config.test.js',
        'checkjs-config.test.js',
        'runtime-dependencies.test.js',
    ],
    sim: [
        'selfplay.test.js',
        'tune-expert.test.js',
        'train-expert-crowd.test.js',
    ],
    core: [
        'gamemanager.test.js',
        'pending-action-queue.test.js',
        'game-turn-policy.test.js',
        'game-dice-policy.test.js',
        'game-card-activation-policy.test.js',
        'game-build-policy.test.js',
        'game-coin-transaction.test.js',
        'game-pending-transition.test.js',
        'game-pending-resolution-policy.test.js',
        'action-ui-registry.test.js',
        'card-contract.test.js',
        'integration.test.js',
        'main.test.js',
        'client-reporting.test.js',
        'confetti.test.js',
        'stats.test.js',
        'ui-log-display.test.js',
        'ui-card-order.test.js',
        'ui-card-detail.test.js',
        'ui-player-display.test.js',
        'ui-input-policy.test.js',
        'game-selection-state.test.js',
        'ui-card-select.test.js',
        'ui-tutorial-settings.test.js',
        'ui-tutorial.test.js',
        'ui-dice-choice.test.js',
        'ui-dice-display.test.js',
        'ui-turn-announcer.test.js',
        'ui-modal-open.test.js',
        'ui-modal-close.test.js',
        'ui-modal-policy.test.js',
        'ui-game-status-view.test.js',
        'ui-game-status-effects.test.js',
        'ui-tab-view.test.js',
        'ui-tab-effects.test.js',
        'ui-runtime-snapshot.test.js',
        'ui-render-runtime.test.js',
        'ui-pending-menu.test.js',
        'ui-pending-effects.test.js',
        'ui-watchdog.test.js',
        'ui-dom-snapshot.test.js',
        'ui-recovery-effects.test.js',
        'ui-watchdog-async-recovery.test.js',
        'ui-watchdog-recovery-runtime.test.js',
        'app-shell-ui-lock-runtime.test.js',
        'crash-screen.test.js',
        'crash-screen-effects.test.js',
        'app-shell-crash-runtime.test.js',
        'ui-winner.test.js',
        'ui-winner-effects.test.js',
        'lifecycle-notify.test.js',
        'lifecycle-runtime.test.js',
        'lifecycle-transport.test.js',
        'checkjs-config.test.js',
        'runtime-dependencies.test.js',
        'ui.test.js',
    ],
    online: [
        'gamemanager.test.js',
        'pending-action-queue.test.js',
        'game-turn-policy.test.js',
        'game-dice-policy.test.js',
        'game-card-activation-policy.test.js',
        'game-build-policy.test.js',
        'game-coin-transaction.test.js',
        'game-pending-transition.test.js',
        'game-pending-resolution-policy.test.js',
        'action-ui-registry.test.js',
        'server.test.js',
        'server-dice.test.js',
        'canonical-mirror-metadata.test.js',
        'canonical-mirror-runtime.test.js',
        'canonical-state-store.test.js',
        'canonical-state-repository.test.js',
        'action-acceptance.test.js',
        'action-payload.test.js',
        'action-validation.test.js',
        'action-validation-gateway.test.js',
        'game-lifecycle-reporting.test.js',
        'game-lifecycle-gateway.test.js',
        'report-delivery.test.js',
        'reporting-http-routes.test.js',
        'game-settings.test.js',
        'server-runtime-limits.test.js',
        'game-runtime-loader.test.js',
        'game-start-payload.test.js',
        'game-start-lifecycle.test.js',
        'game-start-admission.test.js',
        'game-start-coordinator.test.js',
        'room-validation.test.js',
        'room-lifecycle.test.js',
        'room-projection.test.js',
        'room-gc-runtime.test.js',
        'process-runtime.test.js',
        'room-socket-runtime.test.js',
        'socket-connection-runtime.test.js',
        'lobby-admission.test.js',
        'lobby-socket-handlers.test.js',
        'reconnect-identity.test.js',
        'rejoin-payload.test.js',
        'rejoin-socket-handler.test.js',
        'action-socket-handler.test.js',
        'recreate-socket-handler.test.js',
        'restore-admission.test.js',
        'existing-room-rejoin.test.js',
        'restore-replay-admission.test.js',
        'restore-preparation.test.js',
        'restore-gateway.test.js',
        'restored-room.test.js',
        'restored-room-runtime.test.js',
        'restore-sanitization.test.js',
        'restore-validation.test.js',
        'restore-audit-payload.test.js',
        'restore-audit-keyring.test.js',
        'restore-audit-runtime.test.js',
        'restore-snapshot-attachment.test.js',
        'hostless-restore-candidate.test.js',
        'hostless-restore-coordinator.test.js',
        'hostless-restore-gateway.test.js',
        'hostless-restore-approval.test.js',
        'hostless-restore-diagnostics.test.js',
        'hostless-restore-runtime.test.js',
        'socket-payload.test.js',
        'socket-e2e-helper.test.js',
        'game-engine.test.js',
        'game-snapshot.test.js',
        'game-schema-negotiation.test.js',
        'game-schema-codec.test.js',
        'game-schema-wire.test.js',
        'recreate-room-payload.test.js',
        'game-schema-recreate-wire.test.js',
        'game-schema-runtime.test.js',
        'game-schema-shadow.test.js',
        'game-engine-authority.test.js',
        'game-engine-client-shadow.test.js',
        'game-engine-determinism.test.js',
        'game-engine-local-shadow.test.js',
        'game-engine-runtime-adapter.test.js',
        'game-schema-shadow-parity.test.js',
        'snapshot-contract.test.js',
        'client-checkpoint.test.js',
        'client-error-reporting.test.js',
        'client-error-gateway.test.js',
        'client-reporting-transport.test.js',
        'app-shell-client-reporting-runtime.test.js',
        'client-event-runtime.test.js',
        'reporting-policy.test.js',
        'report-throttle.test.js',
        'online-setup-state.test.js',
        'online-player-settings.test.js',
        'online-lobby-request-state.test.js',
        'online-hostless-restore-state.test.js',
        'online-storage.test.js',
        'online.test.js',
        'online-payload.test.js',
        'online-restore-queue.test.js',
        'online-restore-queue-state.test.js',
        'online-restore-lifecycle-state.test.js',
        'online-reconnect-cleanup.test.js',
        'online-reconnect-request.test.js',
        'online-restore-abort.test.js',
        'online-action-timeout.test.js',
        'online-decode-failure.test.js',
        'online-action-apply-failure.test.js',
        'online-action-gap.test.js',
        'online-action-no-game.test.js',
        'online-action-commit.test.js',
        'online-socket-connect.test.js',
        'online-socket-registry.test.js',
        'online-socket-disconnect.test.js',
        'online-host-changed.test.js',
        'online-rejoin-persistence.test.js',
        'online-pending-outbound-state.test.js',
        'online-pending-resend.test.js',
        'online-restore-replay.test.js',
        'online-restore-activation.test.js',
        'online-restore-rank.test.js',
        'online-action-sequence.test.js',
        'online-action-log.test.js',
        'online-session-lifecycle.test.js',
        'online-reconnect-state.test.js',
        'online-runtime-state.test.js',
        'online-client-effects.test.js',
        'online-dom-effects.test.js',
        'online-socket-effects.test.js',
        'online-runtime-flags.test.js',
        'online-diagnostic-state.test.js',
        'online-schema-transport.test.js',
        'online-retry-policy.test.js',
        'online-integration.test.js',
        'online-delivery-smoke.test.js',
        'online-delivery-handshake.test.js',
        'online-action-reconnect-e2e.test.js',
        'online-completion-e2e.test.js',
        'game-schema-online-e2e.test.js',
        'storage.test.js',
    ],
    pwa: [
        'storage.test.js',
        'client-storage.test.js',
        'app-shell-storage.test.js',
        'app-shell-runtime-effects.test.js',
        'app-shell-observation-runtime.test.js',
        'action-ui-registry.test.js',
        'main.test.js',
        'static-assets.test.js',
        'sw.test.js',
    ],
    release: [
        'release-e2e.test.js',
    ],
    'cpu-smoke': [
        'cpu.test.js',
    ],
    cpu: [
        'cpu.test.js',
        'cpu-profile.test.js',
        'cpu-selection.test.js',
        'cpu-evaluation.test.js',
        'cpu-legal-moves.test.js',
        'cpu-business-moves.test.js',
        'cpu-action-proposal.test.js',
        'cpu-build-execution.test.js',
        'cpu-simulation.test.js',
        'cpu-decision-snapshot.test.js',
        'cpu-decision-baseline.test.js',
        'cpu-selfplay-regression.test.js',
        'selfplay.test.js',
        'tune-expert.test.js',
        'train-expert-crowd.test.js',
        'eval-expert-v2-benchmark-pack.test.js',
        'eval-expert-v2-multiseed.test.js',
        'eval-expert-vs-strong.test.js',
        'eval-expert-vs-normal.test.js',
        'eval-expert-vs-weak.test.js',
        'diagnose-expert-losses.test.js',
        'summarize-expert-losses-json.test.js',
        'diagnose-expert-v2-branches.test.js',
        'search-expert-top-tier.test.js',
    ],
    rl: [
        'rlcpu.test.js',
        'rl-model-portfolio.test.js',
        'validate-rl-registry.test.js',
        'report-rl-registry.test.js',
        'audit-rl-portfolio.test.js',
        'plan-rl-next-actions.test.js',
        'review-rl-adoptions.test.js',
        'refresh-rl-ops-reports.test.js',
        'report-rl-diversity.test.js',
        'review-rl-multiplayer-topk.test.js',
        'review-rl-multiplayer-experiment-set.test.js',
        'rl-train.test.js',
        'rl-match-trace.test.js',
        'compare-rl-match-trace.test.js',
        'js-cpu-oracle.test.js',
        'resolve-rl-model-path.test.js',
        'eval-rl-vs-js.test.js',
        'eval-rl-models.test.js',
        'diagnose-rl-build-pass.test.js',
        'diagnose-rl-landmark-race.test.js',
        'render-rl-registry-evals.test.js',
        'update-rl-registry-from-eval.test.js',
        'eval-rl-business-scenario.test.js',
        'eval-rl-special-scenarios.test.js',
        'summarize-rl-metrics.test.js',
        'cli-args.test.js',
    ],
    soak: [
        'online-soak.test.js',
    ],
};

const repoRoot = path.join(__dirname, '..');

const REQUIRED_TEST_GROUPS = Object.freeze({
    'online-action-reconnect-e2e.test.js': ['online'],
    'online-completion-e2e.test.js': ['online'],
    'game-schema-online-e2e.test.js': ['online'],
    'online-soak.test.js': ['soak'],
});

function listActualTestFiles() {
    return fs.readdirSync(__dirname)
        .filter(file => file.endsWith('.test.js'))
        .sort();
}

function validateTestGroups() {
    const actualFiles = listActualTestFiles();
    const actualSet = new Set(actualFiles);
    const listedFiles = new Set();
    const errors = [];

    for (const [group, files] of Object.entries(TEST_GROUPS)) {
        const seenInGroup = new Set();
        for (const file of files) {
            if (seenInGroup.has(file)) {
                errors.push(`${group}: duplicate test entry ${file}`);
            }
            seenInGroup.add(file);
            listedFiles.add(file);
            if (!actualSet.has(file)) {
                errors.push(`${group}: listed test file does not exist: ${file}`);
            }
        }
    }

    for (const [file, requiredGroups] of Object.entries(REQUIRED_TEST_GROUPS)) {
        for (const group of requiredGroups) {
            if (!TEST_GROUPS[group] || !TEST_GROUPS[group].includes(file)) {
                errors.push(`${file}: must belong to ${group} test group`);
            }
        }
    }
    for (const file of actualFiles) {
        if (/^online(?:-|\.)/.test(file) && file !== 'online-soak.test.js' && !TEST_GROUPS.online.includes(file)) {
            errors.push(`${file}: online-prefixed tests must belong to online test group`);
        }
    }

    for (const file of actualFiles) {
        if (!listedFiles.has(file)) {
            errors.push(`unlisted test file: ${file}`);
        }
    }

    if (errors.length > 0) {
        console.error('[test runner] invalid test groups:');
        for (const error of errors) console.error(`- ${error}`);
        process.exit(1);
    }
}

const mode = process.argv[2] || 'unit';
validateTestGroups();

if (mode !== 'all' && !Object.prototype.hasOwnProperty.call(TEST_GROUPS, mode)) {
    console.error(`[test runner] unknown test group: ${mode}`);
    console.error(`[test runner] available groups: ${['all', ...Object.keys(TEST_GROUPS)].join(', ')}`);
    process.exit(1);
}

const testFiles = mode === 'all'
    ? [...TEST_GROUPS.unit, ...TEST_GROUPS.sim]
    : TEST_GROUPS[mode];

async function main() {
    const env = mode === 'cpu-smoke'
        ? Object.assign({}, process.env, { MACHIKORO_CPU_SMOKE: '1' })
        : process.env;
    const result = await runTestFiles(testFiles, {
        concurrency: resolveTestConcurrency(mode),
        env,
        repoRoot,
        testDir: __dirname,
    });
    if (result.failed) process.exitCode = 1;
}

main().catch(error => {
    console.error(error && error.stack || error);
    process.exitCode = 1;
});
