const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { runTest } = require('./helpers/test-utils');

function assertDependencyOrder(file, dependencies) {
    const source = fs.readFileSync(path.join(__dirname, '..', file), 'utf8');

    for (const chain of dependencies) {
        for (let index = 0; index < chain.length - 1; index++) {
            const dependency = chain[index];
            const consumer = chain[index + 1];
            const dependencyIndex = source.indexOf(dependency);
            const consumerIndex = source.indexOf(consumer);

            assert.ok(dependencyIndex >= 0, `${file}: missing ${dependency}`);
            assert.ok(consumerIndex >= 0, `${file}: missing ${consumer}`);
            assert.ok(
                dependencyIndex < consumerIndex,
                `${file}: ${dependency} must load before ${consumer}`
            );
        }
    }
}

runTest('productionと主要runtimeは抽出moduleをconsumerより先に読み込む', () => {
    const cases = [
        ['index.html', [
            ['js/Card.js', 'js/Player.js', 'js/gameSelectionState.js', 'js/gameSetupState.js', 'js/onlineRuntimeState.js', 'js/onlineSetupState.js', 'js/online.js'],
            ['js/gameSelectionState.js', 'js/ui.js'],
            ['js/gameSetupState.js', 'js/ui.js'],
            ['js/gameSelectionState.js', 'js/gameSetupState.js', 'js/storage.js'],
            ['js/gameRuntimeState.js', 'js/online.js'],
            ['js/gameRuntimeState.js', 'js/onlineRuntimeState.js', 'js/ui.js'],
            ['js/gameRuntimeState.js', 'js/onlineRuntimeState.js', 'js/storage.js'],
            ['js/gameRuntimeState.js', 'js/onlineRuntimeState.js', 'js/appShell.js'],
            ['js/gameSelectionState.js', 'js/gameSetupState.js', 'js/main.js'],
            ['js/gameRuntimeState.js', 'js/onlineRuntimeState.js', 'js/main.js'],
            ['js/actionContract.js', 'js/pendingActionQueue.js', 'js/gameTurnPolicy.js', 'js/gameDicePolicy.js', 'js/gameCardActivationPolicy.js', 'js/gameBuildPolicy.js', 'js/gameCoinTransaction.js', 'js/gamePendingTransition.js', 'js/gamePendingResolutionPolicy.js', 'js/GameManager.js'],
            ['js/cpuProfile.js', 'js/cpuSelection.js', 'js/CPU.js'],
            ['js/cpuLegalMoves.js', 'js/CPU.js'],
            ['js/cpuBusinessMoves.js', 'js/CPU.js'],
            ['js/cpuActionProposal.js', 'js/cpuBuildExecution.js'],
            ['js/cpuBuildExecution.js', 'js/CPU.js'],
            ['js/cpuSimulation.js', 'js/CPU.js'],
            ['js/cpuEvaluation.js', 'js/CPU.js'],
            ['js/actionContract.js', 'js/gameEngine.js'],
            ['js/gameEngine.js', 'js/gameEngineDeterminism.js'],
            ['js/gameEngineDeterminism.js', 'js/main.js'],
            ['js/gameSnapshot.js', 'js/gameEngineRuntimeAdapter.js'],
            ['js/gameEngineRuntimeAdapter.js', 'js/online.js'],
            ['js/gameSnapshot.js', 'js/gameEngine.js'],
            ['js/gameSnapshot.js', 'js/localSaveRepository.js'],
            ['js/actionContract.js', 'js/gameSchemaCodec.js'],
            ['js/gameSchemaNegotiation.js', 'js/gameSchemaCodec.js'],
            ['js/gameSnapshot.js', 'js/gameSchemaCodec.js'],
            ['js/gameSchemaCodec.js', 'js/gameSchemaWire.js'],
            ['js/gameSchemaWire.js', 'js/online.js'],
            ['js/recreateRoomPayload.js', 'js/gameSchemaRecreateWire.js'],
            ['js/gameSchemaWire.js', 'js/gameSchemaRecreateWire.js'],
            ['js/gameSchemaRecreateWire.js', 'js/online.js'],
            ['js/gameSchemaCodec.js', 'js/gameEngine.js'],
            ['js/gameSnapshot.js', 'js/online.js'],
            ['js/gameEngine.js', 'js/online.js'],
            ['js/gameEngineAuthority.js', 'js/gameEngineClientShadow.js'],
            ['js/gameEngineClientShadow.js', 'js/online.js'],
            ['js/gameSchemaNegotiation.js', 'js/online.js'],
            ['js/clientStorage.js', 'js/onlineStorage.js'],
            ['js/clientStorage.js', 'js/online.js'],
            ['js/onlineStorage.js', 'js/online.js'],
            ['js/onlinePayload.js', 'js/online.js'],
            ['js/onlineRestoreQueueState.js', 'js/online.js'],
            ['js/onlineRestoreLifecycleState.js', 'js/online.js'],
            ['js/onlineRestoreQueue.js', 'js/online.js'],
            ['js/onlineReconnectCleanup.js', 'js/online.js'],
            ['js/onlineReconnectRequest.js', 'js/online.js'],
            ['js/onlineRestoreAbort.js', 'js/online.js'],
            ['js/onlineActionTimeout.js', 'js/online.js'],
            ['js/onlineDecodeFailure.js', 'js/online.js'],
            ['js/onlineActionApplyFailure.js', 'js/online.js'],
            ['js/onlineActionGap.js', 'js/online.js'],
            ['js/onlineActionNoGame.js', 'js/online.js'],
            ['js/onlineActionCommit.js', 'js/online.js'],
            ['js/onlineSocketConnect.js', 'js/onlineSocketRegistry.js', 'js/online.js'],
            ['js/onlineSocketDisconnect.js', 'js/online.js'],
            ['js/onlineHostChanged.js', 'js/online.js'],
            ['js/onlineRejoinPersistence.js', 'js/online.js'],
            ['js/onlinePendingOutboundState.js', 'js/onlinePendingResend.js', 'js/online.js'],
            ['js/onlineRestoreReplay.js', 'js/online.js'],
            ['js/onlineRestoreActivation.js', 'js/online.js'],
            ['js/onlinePlayerSettings.js', 'js/online.js'],
            ['js/onlineLobbyRequestState.js', 'js/online.js'],
            ['js/onlineHostlessRestoreState.js', 'js/online.js'],
            ['js/onlineRestoreRank.js', 'js/online.js'],
            ['js/onlineActionLog.js', 'js/online.js'],
            ['js/onlineSessionLifecycle.js', 'js/online.js'],
            ['js/onlineReconnectState.js', 'js/online.js'],
            ['js/onlineRuntimeFlags.js', 'js/online.js'],
            ['js/onlineDiagnosticState.js', 'js/online.js'],
            ['js/onlineSchemaTransport.js', 'js/onlineClientEffects.js', 'js/onlineDomEffects.js', 'js/onlineSocketEffects.js', 'js/online.js'],
            ['js/onlineRetryPolicy.js', 'js/online.js'],
            ['js/clientStorage.js', 'js/ui.js'],
            ['js/uiLogDisplay.js', 'js/ui.js'],
            ['js/uiCardOrder.js', 'js/ui.js'],
            ['js/uiPlayerDisplay.js', 'js/ui.js'],
            ['js/uiInputPolicy.js', 'js/ui.js'],
            ['js/uiBuildMenu.js', 'js/ui.js'],
            ['js/uiPendingMenu.js', 'js/ui.js'],
            ['js/uiPendingEffects.js', 'js/ui.js'],
            ['js/uiCardDetail.js', 'js/ui.js'],
            ['js/uiCardSelect.js', 'js/ui.js'],
            ['js/uiTutorialSettings.js', 'js/ui.js'],
            ['js/uiTutorial.js', 'js/ui.js'],
            ['js/uiDiceChoice.js', 'js/ui.js'],
            ['js/uiDiceDisplay.js', 'js/main.js'],
            ['js/uiTurnAnnouncer.js', 'js/ui.js'],
            ['js/uiModalPolicy.js', 'js/ui.js'],
            ['js/uiModalOpen.js', 'js/ui.js'],
            ['js/uiModalClose.js', 'js/ui.js'],
            ['js/uiWinner.js', 'js/uiWinnerEffects.js', 'js/ui.js'],
            ['js/uiGameStatusView.js', 'js/uiGameStatusEffects.js', 'js/ui.js'],
            ['js/uiTabView.js', 'js/uiTabEffects.js', 'js/ui.js'],
            ['js/uiRuntimeSnapshot.js', 'js/ui.js'],
            ['js/uiRenderRuntime.js', 'js/ui.js'],
            ['js/localSaveRepository.js', 'js/storage.js'],
            ['js/localSaveRuntime.js', 'js/storage.js'],
            ['js/localResumePolicy.js', 'js/storage.js'],
            ['js/localResumePreloadState.js', 'js/storage.js'],
            ['js/localResumeView.js', 'js/storage.js'],
            ['js/storedOnlineReconnect.js', 'js/storage.js'],
            ['js/savedGameValidation.js', 'js/storage.js'],
            ['js/storageSettings.js', 'js/storage.js'],
            ['js/clientStorage.js', 'js/storage.js'],
            ['js/clientStorage.js', 'js/stats.js'],
            ['js/uiStatsView.js', 'js/stats.js'],
            ['js/clientStorage.js', 'js/appShellStorage.js'],
            ['js/appShellStorage.js', 'js/appShell.js'],
            ['js/clientCheckpoint.js', 'js/appShell.js'],
            ['js/clientReporting.js', 'js/clientReportingTransport.js'],
            ['js/clientReportingTransport.js', 'js/appShell.js'],
            ['js/lifecycleNotify.js', 'js/lifecycleRuntime.js', 'js/appShell.js'],
            ['js/lifecycleTransport.js', 'js/clientEventRuntime.js', 'js/appShell.js'],
            ['js/uiWatchdog.js', 'js/appShell.js'],
            ['js/uiDomSnapshot.js', 'js/uiRecoveryEffects.js', 'js/appShell.js'],
            ['js/uiWatchdogMonitor.js', 'js/appShell.js'],
            ['js/uiWatchdogReporting.js', 'js/appShell.js'],
            ['js/clientRuntimeSnapshot.js', 'js/appShell.js'],
            ['js/crashScreen.js', 'js/appShell.js'],
            ['js/crashScreenEffects.js', 'js/appShell.js'],
            ['js/pwaShell.js', 'js/appShell.js'],
            ['js/actionUiRegistry.js', 'js/appShell.js'],
            ['js/uiTabView.js', 'js/uiTabEffects.js', 'js/appShell.js'],
            ['js/localPlayerSettings.js', 'js/main.js'],
            ['js/localGameStart.js', 'js/main.js'],
            ['js/autoSkipPolicy.js', 'js/main.js'],
            ['js/pageActivationPolicy.js', 'js/main.js'],
            ['js/delayedHumanActionPolicy.js', 'js/main.js'],
            ['js/cpuSchedulerState.js', 'js/main.js'],
            ['js/cpuTurnStrategy.js', 'js/main.js'],
            ['js/localActionPolicy.js', 'js/main.js'],
            ['js/uiEventDelegation.js', 'js/main.js'],
            ['js/citySkyline.js', 'js/main.js'],
        ]],
        ['scripts/selfplay.js', [
            ['js/actionContract.js', 'js/pendingActionQueue.js', 'js/gameTurnPolicy.js', 'js/gameDicePolicy.js', 'js/gameCardActivationPolicy.js', 'js/gameBuildPolicy.js', 'js/gameCoinTransaction.js', 'js/gamePendingTransition.js', 'js/gamePendingResolutionPolicy.js', 'js/GameManager.js'],
            ['js/actionContract.js', 'js/gameEngine.js'],
            ['js/gameSnapshot.js', 'js/gameEngine.js'],
            ['js/gameSchemaCodec.js', 'js/gameEngine.js'],
            ['js/gameEngine.js', 'js/cpuBuildExecution.js'],
            ['js/cpuProfile.js', 'js/cpuSelection.js', 'js/CPU.js'],
            ['js/cpuLegalMoves.js', 'js/CPU.js'],
            ['js/cpuBusinessMoves.js', 'js/CPU.js'],
            ['js/cpuActionProposal.js', 'js/cpuBuildExecution.js'],
            ['js/cpuBuildExecution.js', 'js/CPU.js'],
            ['js/cpuSimulation.js', 'js/CPU.js'],
            ['js/cpuEvaluation.js', 'js/CPU.js']
        ]],
        ['tests/helpers/runtime-loaders.js', [
            ['js/actionContract.js', 'js/pendingActionQueue.js', 'js/gameTurnPolicy.js', 'js/gameDicePolicy.js', 'js/gameCardActivationPolicy.js', 'js/gameBuildPolicy.js', 'js/gameCoinTransaction.js', 'js/gamePendingTransition.js', 'js/gamePendingResolutionPolicy.js', 'js/GameManager.js'],
            ['js/actionContract.js', 'js/gameEngine.js'],
            ['js/gameSnapshot.js', 'js/gameEngine.js'],
            ['js/gameSchemaCodec.js', 'js/gameEngine.js'],
            ['js/gameEngine.js', 'js/cpuBuildExecution.js'],
            ['js/cpuProfile.js', 'js/cpuSelection.js', 'js/CPU.js'],
            ['js/cpuLegalMoves.js', 'js/CPU.js'],
            ['js/cpuBusinessMoves.js', 'js/CPU.js'],
            ['js/cpuActionProposal.js', 'js/cpuBuildExecution.js'],
            ['js/cpuBuildExecution.js', 'js/CPU.js'],
            ['js/cpuSimulation.js', 'js/CPU.js'],
            ['js/cpuEvaluation.js', 'js/CPU.js']
        ]],
        ['tests/helpers/integration-runtime.js', [
            ['js/Card.js', 'js/Player.js', 'js/gameSelectionState.js', 'js/gameSetupState.js', 'js/onlineRuntimeState.js', 'js/onlineSetupState.js', 'js/online.js'],
            ['js/gameSelectionState.js', 'js/ui.js'],
            ['js/gameSetupState.js', 'js/ui.js'],
            ['js/gameSelectionState.js', 'js/gameSetupState.js', 'js/storage.js'],
            ['js/gameRuntimeState.js', 'js/online.js'],
            ['js/gameRuntimeState.js', 'js/onlineRuntimeState.js', 'js/ui.js'],
            ['js/gameRuntimeState.js', 'js/onlineRuntimeState.js', 'js/storage.js'],
            ['js/gameRuntimeState.js', 'js/onlineRuntimeState.js', 'js/appShell.js'],
            ['js/gameSelectionState.js', 'js/gameSetupState.js', 'js/main.js'],
            ['js/gameRuntimeState.js', 'js/onlineRuntimeState.js', 'js/main.js'],
            ['js/actionContract.js', 'js/pendingActionQueue.js', 'js/gameTurnPolicy.js', 'js/gameDicePolicy.js', 'js/gameCardActivationPolicy.js', 'js/gameBuildPolicy.js', 'js/gameCoinTransaction.js', 'js/gamePendingTransition.js', 'js/gamePendingResolutionPolicy.js', 'js/GameManager.js'],
            ['js/cpuProfile.js', 'js/cpuSelection.js', 'js/CPU.js'],
            ['js/cpuLegalMoves.js', 'js/CPU.js'],
            ['js/cpuBusinessMoves.js', 'js/CPU.js'],
            ['js/cpuActionProposal.js', 'js/cpuBuildExecution.js'],
            ['js/cpuBuildExecution.js', 'js/CPU.js'],
            ['js/cpuSimulation.js', 'js/CPU.js'],
            ['js/cpuEvaluation.js', 'js/CPU.js'],
            ['js/clientStorage.js', 'js/appShellStorage.js'],
            ['js/appShellStorage.js', 'js/appShell.js'],
            ['js/clientCheckpoint.js', 'js/appShell.js'],
            ['js/clientReporting.js', 'js/clientReportingTransport.js'],
            ['js/clientReportingTransport.js', 'js/appShell.js'],
            ['js/lifecycleNotify.js', 'js/lifecycleRuntime.js', 'js/appShell.js'],
            ['js/lifecycleTransport.js', 'js/clientEventRuntime.js', 'js/appShell.js'],
            ['js/uiWatchdog.js', 'js/appShell.js'],
            ['js/uiDomSnapshot.js', 'js/uiRecoveryEffects.js', 'js/appShell.js'],
            ['js/uiWatchdogMonitor.js', 'js/appShell.js'],
            ['js/uiWatchdogReporting.js', 'js/appShell.js'],
            ['js/clientRuntimeSnapshot.js', 'js/appShell.js'],
            ['js/crashScreen.js', 'js/appShell.js'],
            ['js/crashScreenEffects.js', 'js/appShell.js'],
            ['js/pwaShell.js', 'js/appShell.js'],
            ['js/actionUiRegistry.js', 'js/appShell.js'],
            ['js/uiTabView.js', 'js/uiTabEffects.js', 'js/appShell.js'],
            ['js/localPlayerSettings.js', 'js/main.js'],
            ['js/localGameStart.js', 'js/main.js'],
            ['js/autoSkipPolicy.js', 'js/main.js'],
            ['js/pageActivationPolicy.js', 'js/main.js'],
            ['js/delayedHumanActionPolicy.js', 'js/main.js'],
            ['js/cpuSchedulerState.js', 'js/main.js'],
            ['js/cpuTurnStrategy.js', 'js/main.js'],
            ['js/localActionPolicy.js', 'js/main.js'],
            ['js/uiEventDelegation.js', 'js/main.js'],
            ['js/citySkyline.js', 'js/main.js'],
            ['js/localSaveRepository.js', 'js/storage.js'],
            ['js/localSaveRuntime.js', 'js/storage.js'],
            ['js/localResumePolicy.js', 'js/storage.js'],
            ['js/localResumePreloadState.js', 'js/storage.js'],
            ['js/localResumeView.js', 'js/storage.js'],
            ['js/storedOnlineReconnect.js', 'js/storage.js'],
            ['js/savedGameValidation.js', 'js/storage.js'],
            ['js/storageSettings.js', 'js/storage.js'],
            ['js/clientStorage.js', 'js/storage.js'],
            ['js/clientStorage.js', 'js/stats.js'],
            ['js/uiStatsView.js', 'js/stats.js'],
            ['js/clientStorage.js', 'js/ui.js'],
            ['js/uiLogDisplay.js', 'js/ui.js'],
            ['js/uiCardOrder.js', 'js/ui.js'],
            ['js/uiPlayerDisplay.js', 'js/ui.js'],
            ['js/uiInputPolicy.js', 'js/ui.js'],
            ['js/uiBuildMenu.js', 'js/ui.js'],
            ['js/uiPendingMenu.js', 'js/ui.js'],
            ['js/uiPendingEffects.js', 'js/ui.js'],
            ['js/uiCardDetail.js', 'js/ui.js'],
            ['js/uiCardSelect.js', 'js/ui.js'],
            ['js/uiTutorialSettings.js', 'js/ui.js'],
            ['js/uiTutorial.js', 'js/ui.js'],
            ['js/uiDiceChoice.js', 'js/ui.js'],
            ['js/uiDiceDisplay.js', 'js/main.js'],
            ['js/uiTurnAnnouncer.js', 'js/ui.js'],
            ['js/uiModalPolicy.js', 'js/ui.js'],
            ['js/uiModalOpen.js', 'js/ui.js'],
            ['js/uiModalClose.js', 'js/ui.js'],
            ['js/uiWinner.js', 'js/uiWinnerEffects.js', 'js/ui.js'],
            ['js/uiGameStatusView.js', 'js/uiGameStatusEffects.js', 'js/ui.js'],
            ['js/uiTabView.js', 'js/uiTabEffects.js', 'js/ui.js'],
            ['js/uiRuntimeSnapshot.js', 'js/ui.js'],
            ['js/uiRenderRuntime.js', 'js/ui.js'],
            ['js/actionContract.js', 'js/gameEngine.js'],
            ['js/gameEngine.js', 'js/gameEngineDeterminism.js'],
            ['js/gameEngineDeterminism.js', 'js/main.js'],
            ['js/gameSnapshot.js', 'js/gameEngineRuntimeAdapter.js'],
            ['js/gameEngineRuntimeAdapter.js', 'js/online.js'],
            ['js/gameSnapshot.js', 'js/gameEngine.js'],
            ['js/gameSnapshot.js', 'js/localSaveRepository.js'],
            ['js/actionContract.js', 'js/gameSchemaCodec.js'],
            ['js/gameSchemaNegotiation.js', 'js/gameSchemaCodec.js'],
            ['js/gameSnapshot.js', 'js/gameSchemaCodec.js'],
            ['js/gameSchemaCodec.js', 'js/gameSchemaWire.js'],
            ['js/gameSchemaWire.js', 'js/online.js'],
            ['js/recreateRoomPayload.js', 'js/gameSchemaRecreateWire.js'],
            ['js/gameSchemaWire.js', 'js/gameSchemaRecreateWire.js'],
            ['js/gameSchemaRecreateWire.js', 'js/online.js'],
            ['js/gameSchemaCodec.js', 'js/gameEngine.js'],
            ['js/gameSnapshot.js', 'js/online.js'],
            ['js/gameEngine.js', 'js/online.js'],
            ['js/gameEngineAuthority.js', 'js/gameEngineClientShadow.js'],
            ['js/gameEngineClientShadow.js', 'js/online.js'],
            ['js/gameSchemaNegotiation.js', 'js/online.js'],
            ['js/clientStorage.js', 'js/onlineStorage.js'],
            ['js/clientStorage.js', 'js/online.js'],
            ['js/onlineStorage.js', 'js/online.js'],
            ['js/onlinePayload.js', 'js/online.js'],
            ['js/onlineRestoreQueueState.js', 'js/online.js'],
            ['js/onlineRestoreLifecycleState.js', 'js/online.js'],
            ['js/onlineRestoreQueue.js', 'js/online.js'],
            ['js/onlineReconnectCleanup.js', 'js/online.js'],
            ['js/onlineReconnectRequest.js', 'js/online.js'],
            ['js/onlineRestoreAbort.js', 'js/online.js'],
            ['js/onlineActionTimeout.js', 'js/online.js'],
            ['js/onlineDecodeFailure.js', 'js/online.js'],
            ['js/onlineActionApplyFailure.js', 'js/online.js'],
            ['js/onlineActionGap.js', 'js/online.js'],
            ['js/onlineActionNoGame.js', 'js/online.js'],
            ['js/onlineActionCommit.js', 'js/online.js'],
            ['js/onlineSocketConnect.js', 'js/onlineSocketRegistry.js', 'js/online.js'],
            ['js/onlineSocketDisconnect.js', 'js/online.js'],
            ['js/onlineHostChanged.js', 'js/online.js'],
            ['js/onlineRejoinPersistence.js', 'js/online.js'],
            ['js/onlinePendingOutboundState.js', 'js/onlinePendingResend.js', 'js/online.js'],
            ['js/onlineRestoreReplay.js', 'js/online.js'],
            ['js/onlineRestoreActivation.js', 'js/online.js'],
            ['js/onlinePlayerSettings.js', 'js/online.js'],
            ['js/onlineLobbyRequestState.js', 'js/online.js'],
            ['js/onlineHostlessRestoreState.js', 'js/online.js'],
            ['js/onlineRestoreRank.js', 'js/online.js'],
            ['js/onlineActionLog.js', 'js/online.js'],
            ['js/onlineSessionLifecycle.js', 'js/online.js'],
            ['js/onlineReconnectState.js', 'js/online.js'],
            ['js/onlineRuntimeFlags.js', 'js/online.js'],
            ['js/onlineDiagnosticState.js', 'js/online.js'],
            ['js/onlineSchemaTransport.js', 'js/onlineClientEffects.js', 'js/onlineDomEffects.js', 'js/onlineSocketEffects.js', 'js/online.js'],
            ['js/onlineRetryPolicy.js', 'js/online.js'],
        ]],
        ['tests/stats.test.js', [
            ['js/clientStorage.js', 'js/stats.js'],
            ['js/uiStatsView.js', 'js/stats.js'],
        ]],
        ['tests/ui.test.js', [
            ['js/Card.js', 'js/Player.js', 'js/gameSelectionState.js', 'js/ui.js'],
            ['js/clientStorage.js', 'js/ui.js'],
            ['js/uiLogDisplay.js', 'js/ui.js'],
            ['js/uiCardOrder.js', 'js/ui.js'],
            ['js/uiPlayerDisplay.js', 'js/ui.js'],
            ['js/uiInputPolicy.js', 'js/ui.js'],
            ['js/uiBuildMenu.js', 'js/ui.js'],
            ['js/uiPendingMenu.js', 'js/ui.js'],
            ['js/uiPendingEffects.js', 'js/ui.js'],
            ['js/uiCardDetail.js', 'js/ui.js'],
            ['js/uiCardSelect.js', 'js/ui.js'],
            ['js/uiTutorialSettings.js', 'js/ui.js'],
            ['js/uiTutorial.js', 'js/ui.js'],
            ['js/uiDiceChoice.js', 'js/ui.js'],
            ['js/uiModalPolicy.js', 'js/ui.js'],
            ['js/uiModalOpen.js', 'js/ui.js'],
            ['js/uiModalClose.js', 'js/ui.js'],
            ['js/uiWinner.js', 'js/uiWinnerEffects.js', 'js/ui.js'],
            ['js/uiGameStatusView.js', 'js/uiGameStatusEffects.js', 'js/ui.js'],
            ['js/uiTabView.js', 'js/uiTabEffects.js', 'js/ui.js'],
            ['js/uiRuntimeSnapshot.js', 'js/ui.js'],
            ['js/uiRenderRuntime.js', 'js/ui.js'],
        ]],
        ['tests/online.test.js', [
            ['js/actionContract.js', 'js/gameEngine.js'],
            ['js/gameSnapshot.js', 'js/gameEngineRuntimeAdapter.js'],
            ['js/gameEngineRuntimeAdapter.js', 'js/online.js'],
            ['js/gameSnapshot.js', 'js/gameEngine.js'],
            ['js/actionContract.js', 'js/gameSchemaCodec.js'],
            ['js/gameSchemaNegotiation.js', 'js/gameSchemaCodec.js'],
            ['js/gameSnapshot.js', 'js/gameSchemaCodec.js'],
            ['js/gameSchemaCodec.js', 'js/gameSchemaWire.js'],
            ['js/gameSchemaWire.js', 'js/online.js'],
            ['js/recreateRoomPayload.js', 'js/gameSchemaRecreateWire.js'],
            ['js/gameSchemaWire.js', 'js/gameSchemaRecreateWire.js'],
            ['js/gameSchemaRecreateWire.js', 'js/online.js'],
            ['js/gameSchemaCodec.js', 'js/gameEngine.js'],
            ['js/gameSnapshot.js', 'js/online.js'],
            ['js/gameEngine.js', 'js/online.js'],
            ['js/gameEngineAuthority.js', 'js/gameEngineClientShadow.js'],
            ['js/gameEngineClientShadow.js', 'js/online.js'],
            ['js/gameSchemaNegotiation.js', 'js/online.js'],
            ['js/clientStorage.js', 'js/onlineStorage.js'],
            ['js/clientStorage.js', 'js/online.js'],
            ['js/onlineStorage.js', 'js/online.js'],
            ['js/onlinePayload.js', 'js/online.js'],
            ['js/onlineRestoreQueueState.js', 'js/online.js'],
            ['js/onlineRestoreLifecycleState.js', 'js/online.js'],
            ['js/onlineRestoreQueue.js', 'js/online.js'],
            ['js/onlineReconnectCleanup.js', 'js/online.js'],
            ['js/onlineReconnectRequest.js', 'js/online.js'],
            ['js/onlineRestoreAbort.js', 'js/online.js'],
            ['js/onlineActionTimeout.js', 'js/online.js'],
            ['js/onlineDecodeFailure.js', 'js/online.js'],
            ['js/onlineActionApplyFailure.js', 'js/online.js'],
            ['js/onlineActionGap.js', 'js/online.js'],
            ['js/onlineActionNoGame.js', 'js/online.js'],
            ['js/onlineActionCommit.js', 'js/online.js'],
            ['js/onlineSocketConnect.js', 'js/onlineSocketRegistry.js', 'js/online.js'],
            ['js/onlineSocketDisconnect.js', 'js/online.js'],
            ['js/onlineHostChanged.js', 'js/online.js'],
            ['js/onlineRejoinPersistence.js', 'js/online.js'],
            ['js/onlinePendingOutboundState.js', 'js/onlinePendingResend.js', 'js/online.js'],
            ['js/onlineRestoreReplay.js', 'js/online.js'],
            ['js/onlineRestoreActivation.js', 'js/online.js'],
            ['js/onlinePlayerSettings.js', 'js/online.js'],
            ['js/onlineLobbyRequestState.js', 'js/online.js'],
            ['js/onlineHostlessRestoreState.js', 'js/online.js'],
            ['js/onlineRestoreRank.js', 'js/online.js'],
            ['js/onlineActionLog.js', 'js/online.js'],
            ['js/onlineSessionLifecycle.js', 'js/online.js'],
            ['js/onlineReconnectState.js', 'js/online.js'],
            ['js/onlineRuntimeFlags.js', 'js/online.js'],
            ['js/onlineDiagnosticState.js', 'js/online.js'],
            ['js/onlineSchemaTransport.js', 'js/onlineClientEffects.js', 'js/onlineDomEffects.js', 'js/onlineSocketEffects.js', 'js/online.js'],
            ['js/onlineRetryPolicy.js', 'js/online.js'],
        ]],
        ['tests/release-e2e.test.js', [
            ['js/Card.js', 'js/Player.js', 'js/gameSelectionState.js', 'js/ui.js'],
            ['js/actionContract.js', 'js/actionUiRegistry.js'],
            ['js/clientStorage.js', 'js/ui.js'],
            ['js/uiLogDisplay.js', 'js/ui.js'],
            ['js/uiCardOrder.js', 'js/ui.js'],
            ['js/uiInputPolicy.js', 'js/ui.js'],
            ['js/clientStorage.js', 'js/appShellStorage.js'],
            ['js/appShellStorage.js', 'js/appShell.js'],
            ['js/clientCheckpoint.js', 'js/appShell.js'],
            ['js/clientReporting.js', 'js/clientReportingTransport.js'],
            ['js/clientReportingTransport.js', 'js/appShell.js'],
            ['js/lifecycleNotify.js', 'js/lifecycleRuntime.js', 'js/appShell.js'],
            ['js/lifecycleTransport.js', 'js/clientEventRuntime.js', 'js/appShell.js'],
            ['js/uiWatchdog.js', 'js/appShell.js'],
            ['js/uiDomSnapshot.js', 'js/uiRecoveryEffects.js', 'js/appShell.js'],
            ['js/uiWatchdogMonitor.js', 'js/appShell.js'],
            ['js/uiWatchdogReporting.js', 'js/appShell.js'],
            ['js/clientRuntimeSnapshot.js', 'js/appShell.js'],
            ['js/crashScreen.js', 'js/appShell.js'],
            ['js/crashScreenEffects.js', 'js/appShell.js'],
            ['js/pwaShell.js', 'js/appShell.js'],
            ['js/actionUiRegistry.js', 'js/appShell.js'],
            ['js/uiTabView.js', 'js/uiTabEffects.js', 'js/appShell.js'],
            ['js/uiPendingMenu.js', 'js/ui.js'],
            ['js/uiPendingEffects.js', 'js/ui.js'],
            ['js/uiTutorialSettings.js', 'js/ui.js'],
            ['js/uiTutorial.js', 'js/ui.js'],
            ['js/uiDiceChoice.js', 'js/ui.js'],
            ['js/uiModalPolicy.js', 'js/ui.js'],
            ['js/uiModalOpen.js', 'js/ui.js'],
            ['js/uiModalClose.js', 'js/ui.js'],
            ['js/uiWinner.js', 'js/uiWinnerEffects.js', 'js/ui.js'],
            ['js/uiGameStatusView.js', 'js/uiGameStatusEffects.js', 'js/ui.js'],
            ['js/uiTabView.js', 'js/uiTabEffects.js', 'js/ui.js'],
            ['js/uiRuntimeSnapshot.js', 'js/ui.js'],
            ['js/uiRenderRuntime.js', 'js/ui.js'],
        ]],
        ['tests/main.test.js', [
            ['js/actionContract.js', 'js/actionUiRegistry.js'],
            ['js/gameEngineAuthority.js', 'js/gameEngineClientShadow.js', 'js/main.js'],
            ['js/clientStorage.js', 'js/appShellStorage.js'],
            ['js/appShellStorage.js', 'js/appShell.js'],
            ['js/clientCheckpoint.js', 'js/appShell.js'],
            ['js/clientReporting.js', 'js/clientReportingTransport.js'],
            ['js/clientReportingTransport.js', 'js/appShell.js'],
            ['js/lifecycleNotify.js', 'js/lifecycleRuntime.js', 'js/appShell.js'],
            ['js/lifecycleTransport.js', 'js/clientEventRuntime.js', 'js/appShell.js'],
            ['js/uiWatchdog.js', 'js/appShell.js'],
            ['js/uiDomSnapshot.js', 'js/uiRecoveryEffects.js', 'js/appShell.js'],
            ['js/uiWatchdogMonitor.js', 'js/appShell.js'],
            ['js/uiWatchdogReporting.js', 'js/appShell.js'],
            ['js/clientRuntimeSnapshot.js', 'js/appShell.js'],
            ['js/crashScreen.js', 'js/appShell.js'],
            ['js/crashScreenEffects.js', 'js/appShell.js'],
            ['js/pwaShell.js', 'js/appShell.js'],
            ['js/actionUiRegistry.js', 'js/appShell.js'],
            ['js/uiTabView.js', 'js/uiTabEffects.js', 'js/appShell.js'],
            ['js/localPlayerSettings.js', 'js/main.js'],
            ['js/localGameStart.js', 'js/main.js'],
            ['js/autoSkipPolicy.js', 'js/main.js'],
            ['js/pageActivationPolicy.js', 'js/main.js'],
            ['js/delayedHumanActionPolicy.js', 'js/main.js'],
            ['js/cpuSchedulerState.js', 'js/main.js'],
            ['js/cpuTurnStrategy.js', 'js/main.js'],
            ['js/localActionPolicy.js', 'js/main.js'],
            ['js/uiEventDelegation.js', 'js/main.js'],
            ['js/citySkyline.js', 'js/main.js'],
        ]]
    ];

    for (const [file, dependencies] of cases) {
        assertDependencyOrder(file, dependencies);
    }
});
