declare var GameActionContract: typeof import("../js/actionContract");
declare var GameSnapshot: typeof import("../js/gameSnapshot");
declare var PendingActionQueue: typeof import("../js/pendingActionQueue").PendingActionQueue;
declare var GameTurnPolicy: typeof import("../js/gameTurnPolicy");
declare var GameDicePolicy: typeof import("../js/gameDicePolicy");
declare var GameCardActivationPolicy: typeof import("../js/gameCardActivationPolicy");
declare var GameBuildPolicy: typeof import("../js/gameBuildPolicy");
declare var GameCoinTransaction: typeof import("../js/gameCoinTransaction");
declare var GamePendingTransition: typeof import("../js/gamePendingTransition");
declare var GamePendingResolutionPolicy: typeof import("../js/gamePendingResolutionPolicy");
declare var OnlineSocketRegistry: typeof import("../js/onlineSocketRegistry");
declare var ClientEventRuntime: typeof import("../js/clientEventRuntime");
declare var escapeHtml: ((value: unknown) => string) | undefined;
declare var isOnlineGame: boolean | undefined;
declare var showConfirm: ((message: string, onConfirm: () => void) => void) | undefined;
declare var UiWinnerEffects: typeof import("../js/uiWinnerEffects");
declare var UiGameStatusEffects: typeof import("../js/uiGameStatusEffects");
declare var UiTutorialSettings: typeof import("../js/uiTutorialSettings");
declare var RLModelCatalog: typeof import("../js/rlModelCatalog");

declare var CPUProfile: typeof import("../js/cpuProfile").CPUProfile;
declare var CPUSelection: typeof import("../js/cpuSelection").CPUSelection;
declare var CPUDiagnostics: typeof import("../js/cpuDiagnostics").CPUDiagnostics;
declare var CPUEvaluationCache: typeof import("../js/cpuEvaluationCache").CPUEvaluationCache;
declare var CPUBusinessMoves: typeof import("../js/cpuBusinessMoves").CPUBusinessMoves;
declare var CPUBusinessDecisionRuntime: typeof import("../js/cpuBusinessDecisionRuntime").CPUBusinessDecisionRuntime;
declare var CPUSimulation: typeof import("../js/cpuSimulation").CPUSimulation;
declare var CPUEvaluation: typeof import("../js/cpuEvaluation").CPUEvaluation;
declare var CPUBuildExecution: typeof import("../js/cpuBuildExecution").CPUBuildExecution;
declare var CPUBuildProposalCollector: typeof import("../js/cpuBuildProposalCollector").CPUBuildProposalCollector;
declare var CPUBuildStrategy: typeof import("../js/cpuBuildStrategy").CPUBuildStrategy;
declare var CPUActionProposal: typeof import("../js/cpuActionProposal").CPUActionProposal;
declare var CPUBuildScoring: typeof import("../js/cpuBuildScoring").CPUBuildScoring;
declare var CPUChoiceScoring: typeof import("../js/cpuChoiceScoring").CPUChoiceScoring;
declare var CPUCardEvaluationRuntime: typeof import("../js/cpuCardEvaluationRuntime").CPUCardEvaluationRuntime;
declare var CPUStateEvaluationRuntime: typeof import("../js/cpuStateEvaluationRuntime").CPUStateEvaluationRuntime;
declare var CPUBuildPolicyRuntime: typeof import("../js/cpuBuildPolicyRuntime").CPUBuildPolicyRuntime;
declare var CPULegalMoves: typeof import("../js/cpuLegalMoves").CPULegalMoves;
declare var CPULookaheadRuntime: typeof import("../js/cpuLookaheadRuntime").CPULookaheadRuntime;
declare var CPUPendingResolution: typeof import("../js/cpuPendingResolution").CPUPendingResolution;
declare var CPUPendingDecision: typeof import("../js/cpuPendingDecision").CPUPendingDecision;
declare var CPURollDecision: typeof import("../js/cpuRollDecision").CPURollDecision;
declare var CPU_EXPERT_DEFAULT_OPTIONS: typeof import("../js/cpuTuning").CPU_EXPERT_DEFAULT_OPTIONS;
declare var CPU_EXPERT_PRESETS: typeof import("../js/cpuTuning").CPU_EXPERT_PRESETS;
declare var CPU_EXPERT_PROFILE_TUNINGS: typeof import("../js/cpuTuning").CPU_EXPERT_PROFILE_TUNINGS;
declare var resolveLiveExpertOptions: typeof import("../js/cpuTuning").resolveLiveExpertOptions;
declare var resolveLiveCpuOptions: typeof import("../js/cpuTuning").resolveLiveCpuOptions;
declare var resolveExpertProfileTuning: typeof import("../js/cpuTuning").resolveExpertProfileTuning;


declare var isRoomHost: boolean | undefined;
declare var isReconnectingOnline: boolean | undefined;
declare var socket: { connected?: boolean } | undefined;
declare var sendAction: ((action: string, data: Record<string, unknown>) => boolean) | undefined;
declare var OnlineReconnectRuntime: typeof import("../js/onlineReconnectRuntime");
declare var OnlineGameEngineRuntime: typeof import("../js/onlineGameEngineRuntime");


// Browser-global publication names for the explicitly checked compatibility modules.
interface Window {
    AppShellComposition: typeof import("../js/appShellComposition");
    GameActionContract: typeof import("../js/actionContract");
    RLModelCatalog: unknown;
    GameTurnPolicy: unknown;
    GameDicePolicy: unknown;
    GameCardActivationPolicy: unknown;
    GameBuildPolicy: unknown;
    GameCoinTransaction: unknown;
    GamePendingTransition: unknown;
    GamePendingResolutionPolicy: unknown;
    CPUBusinessMoves: unknown;
    AD_SLOT_CONFIGS: unknown;
    renderAdSlot: unknown;
    mountAdSlot: unknown;
    mountStaticAdSlots: unknown;
    webkitAudioContext: typeof AudioContext;
    GameSnapshot: typeof import("../js/gameSnapshot");
    LocalSaveRepository: unknown;
    LocalResumeView: unknown;
    GameSchemaNegotiation: unknown;
    GameSchemaCodec: unknown;
    OnlineRetryPolicy: unknown;
    OnlineClientEffects: unknown;
    OnlineDomEffects: unknown;
    OnlineSocketEffects: unknown;
    OnlineSocketRegistry: unknown;
    OnlinePlayerSettings: unknown;
    OnlineRoomShare: typeof import("../js/onlineRoomShare");
    OnlineActionLog: unknown;
    OnlineSessionLifecycle: unknown;
    OnlinePendingOutboundState: unknown;
    createOnlineStorageFacade: unknown;
    GameEngine: unknown;
    GameEngineDeterminism: unknown;
    GameEngineAuthority: unknown;
    GameEngineClientShadow: unknown;
    GameEngineRuntimeAdapter: unknown;
    GameSchemaWire: unknown;
    RecreateRoomPayload: unknown;
    GameSchemaRecreateWire: unknown;
    CPUActionProposal: typeof import("../js/cpuActionProposal").CPUActionProposal;
    CPUBuildStrategy: typeof import("../js/cpuBuildStrategy").CPUBuildStrategy;
    OnlineReconnectRuntime: typeof import("../js/onlineReconnectRuntime");
    OnlineGameEngineRuntime: typeof import("../js/onlineGameEngineRuntime");
    OnlineRestoreMetadata: typeof import("../js/onlineRestoreMetadata");
    CPUBuildExecution: unknown;
    CPULegalMoves: unknown;
    CPUProfile: unknown;
    CPUSimulation: unknown;
    CpuTournament: unknown;
    AppDiagnostics: unknown;
    AppBackup: unknown;
    GameSetupPresets: unknown;
    RoomQrCode: unknown;
    UndoPreview: unknown;
    UiTurnPrivacy: unknown;
    SavedGameValidation: unknown;
    StorageSettings: unknown;
    UiBuildMenu: unknown;
    UiCardDetail: unknown;
    UiCardOrder: unknown;
    UiCardSelect: unknown;
    UiLogDisplay: unknown;
    UiModalPolicy: unknown;
    UiModalOpen: unknown;
    UiModalClose: unknown;
    UiPlayerDisplay: unknown;
    UiInputPolicy: unknown;
    UiPendingMenu: unknown;
    UiPendingEffects: unknown;
    UiTutorialSettings: unknown;
    UiTutorial: unknown;
    UiGameStatusView: unknown;
    UiGameStatusEffects: unknown;
    UiTabView: unknown;
    UiTabEffects: unknown;
    UiCpuTournament: unknown;
    UiStatsView: unknown;
    UiDiceChoice: unknown;
    UiDiceDisplay: unknown;
    AutoSkipPolicy: unknown;
    UiTurnAnnouncer: unknown;
    UiWatchdog: unknown;
    UiDomSnapshot: unknown;
    UiRecoveryEffects: unknown;
    UiWatchdogAsyncRecovery: unknown;
    UiWatchdogRecoveryRuntime: unknown;
    AppShellUiLockRuntime: unknown;
    UiWatchdogRuntime: unknown;
    AppShellRuntimeEffects: unknown;
    AppShellObservationRuntime: unknown;
    CrashScreen: unknown;
    AppShellCrashRuntime: unknown;
    UiWinner: unknown;
    UiWinnerEffects: unknown;
    UiPlayerCount: typeof import("../js/uiPlayerCount");
    UiRangeControl: typeof import("../js/uiRangeControl");
    UiScreenFocus: typeof import("../js/uiScreenFocus");
    UiRenderRuntime: unknown;
    LifecycleNotify: unknown;
    LifecycleRuntime: unknown;
    LifecycleTransport: unknown;
    ClientReportingTransport: unknown;
    AppShellClientReportingRuntime: unknown;
    ClientEventRuntime: unknown;
    ClientCheckpoint: unknown;
    LocalPlayerSettings: unknown;
    PageActivationPolicy: unknown;
    CitySkyline: unknown;
    DelayedHumanActionPolicy: unknown;
    CpuSchedulerState: unknown;
    LocalActionPolicy: unknown;
    UiEventDelegation: unknown;
    ClientStorage: unknown;
    AppShellStorage: unknown;
    PwaShell: unknown;
    AppShellStartupRuntime: unknown;
    RetryTimer: typeof import("../js/retryTimer");
    SocketIoDelivery: typeof import("../js/socketIoDelivery");
}
