// Browser globals consumed by the app-shell composition root. These are
// explicitly late-bound because appShell.js loads before main.js and online.js.
declare var AppShellComposition: typeof import("../js/appShellComposition");
declare var AppShellStorage: typeof import("../js/appShellStorage");

declare var AppShellClientReportingRuntime: typeof import("../js/appShellClientReportingRuntime");
declare var AppShellCrashRuntime: typeof import("../js/appShellCrashRuntime");
declare var AppShellObservationRuntime: typeof import("../js/appShellObservationRuntime");
declare var AppShellRuntimeEffects: typeof import("../js/appShellRuntimeEffects");
declare var AppShellStartupRuntime: typeof import("../js/appShellStartupRuntime");
declare var AppShellUiLockRuntime: typeof import("../js/appShellUiLockRuntime");
declare var ActionUiRegistry: typeof import("../js/actionUiRegistry");
declare var ClientCheckpoint: typeof import("../js/clientCheckpoint");
declare var ClientReporting: typeof import("../js/clientReporting").ClientReporting;
declare var ClientReportingTransport: typeof import("../js/clientReportingTransport");
declare var ClientRuntimeSnapshot: typeof import("../js/clientRuntimeSnapshot");
declare var CrashScreen: typeof import("../js/crashScreen");
declare var CrashScreenEffects: typeof import("../js/crashScreenEffects");
declare var GameRuntimeState: typeof import("../js/gameRuntimeState");
declare var GameSetupState: typeof import("../js/gameSetupState");
declare var LifecycleNotify: typeof import("../js/lifecycleNotify");
declare var LifecycleRuntime: typeof import("../js/lifecycleRuntime");
declare var LifecycleTransport: typeof import("../js/lifecycleTransport");
declare var OnlineRetryPolicy: typeof import("../js/onlineRetryPolicy");
declare var OnlineRuntimeState: typeof import("../js/onlineRuntimeState");
declare var PwaShell: typeof import("../js/pwaShell");
declare var RetryTimer: typeof import("../js/retryTimer");
declare var UiDomSnapshot: typeof import("../js/uiDomSnapshot");
declare var UiRecoveryEffects: typeof import("../js/uiRecoveryEffects");
declare var UiScreenFocus: typeof import("../js/uiScreenFocus");
declare var UiTabEffects: typeof import("../js/uiTabEffects");
declare var UiTabView: typeof import("../js/uiTabView");
declare var UiWatchdog: typeof import("../js/uiWatchdog");
declare var UiWatchdogAsyncRecovery: typeof import("../js/uiWatchdogAsyncRecovery");
declare var UiWatchdogMonitor: typeof import("../js/uiWatchdogMonitor");
declare var UiWatchdogRecoveryRuntime: typeof import("../js/uiWatchdogRecoveryRuntime");
declare var UiWatchdogReporting: typeof import("../js/uiWatchdogReporting");
declare var UiWatchdogRuntime: typeof import("../js/uiWatchdogRuntime");

declare var cardFilter: string | undefined;
declare var enabledLandmarks: Set<string> | undefined;
declare var onlineActionInFlight: boolean | undefined;
declare var onlineActionInFlightAt: number | undefined;
declare var SHOP_STOCK: Record<string, number> | undefined;

declare var cancelCpuSchedule: (() => void) | undefined;
declare var closeAccessibleModal: ((id: string, options?: { restoreFocus?: boolean }) => void) | undefined;
declare var closeConfirmModal: ((restoreFocus?: boolean) => void) | undefined;
declare var drawCitySkyline: (() => void) | undefined;
declare var getOnlineActionFlightState: (() => unknown) | undefined;
declare var loadSettings: (() => void) | undefined;
declare var preloadLocalRlModelsInBackground: (() => void) | undefined;
declare var preloadOnlineRlModelsInBackground: (() => void) | undefined;
declare var render: (() => void) | undefined;
declare var renderBuildMenu: (() => void) | undefined;
declare var renderOnlinePlayerSettings: (() => void) | undefined;
declare var resetAccessibleModalRuntimeState: (() => void) | undefined;
declare var resumeGame: (() => void) | undefined;
declare var scheduleCPU: (() => void) | undefined;
declare var updateGameActivityStatus: (() => void) | undefined;
declare var updateGameActivityWatchdogStatus: ((status: unknown) => void) | undefined;
declare var updateResumeButton: (() => void) | undefined;
declare var activeModalId: string | null | undefined;
declare var lastModalFocus: HTMLElement | null | undefined;
declare var modalInertRestore: HTMLElement[] | undefined;
declare var MACHIKORO_CLIENT_VERSION: string | undefined;
declare var __machikoroConfirmModalOpen: boolean | undefined;
declare var __machikoroSetLifecycleNotificationsEnabled: ((enabled: boolean) => void) | undefined;
declare var __machikoroLifecycleNotifyState: unknown;
declare var __machikoroSendLifecycleNotification: ((payload: unknown) => void) | undefined;
declare var __machikoroSendTestErrorReport: ((payload: unknown) => void) | undefined;
declare var cpuSchedulerStateController: unknown;
declare var cpuTurnScheduler: unknown;
declare var _handleOnlineActionTimeout: (() => void) | undefined;
declare var _isOnlineFlowActive: (() => boolean) | undefined;
