declare var DicePresentation: typeof import("../js/dicePresentation");
declare var SharedMarketMount: typeof import("../js/sharedMarketMount");
declare var UiTurnEvents: typeof import("../js/uiTurnEvents");
declare var UiTurnReceipt: typeof import("../js/uiTurnReceipt");
declare var CardBoardFeedback: typeof import("../js/cardBoardFeedback");
declare var UiCardBoard: typeof import("../js/uiCardBoard");
declare var CardBoardField: typeof import("../js/cardBoardField");
declare var UiIncomePreview: typeof import("../js/uiIncomePreview");
declare var UiIncomePreviewPanel: typeof import("../js/uiIncomePreviewPanel");
declare var UiPlayerInsights: typeof import("../js/uiPlayerInsights");
declare var UiPlazaEvents: typeof import("../js/uiPlazaEvents");
declare var UiPlazaFeedback: typeof import("../js/uiPlazaFeedback");
// Exact browser globals consumed by the UI composition root. Keep stateful
// effects optional where the classic-script runtime permits them to be absent.
declare var ClientStorage: typeof import("../js/clientStorage");
declare var GameRuntimeState: typeof import("../js/gameRuntimeState");
declare var GameSelectionState: typeof import("../js/gameSelectionState");
declare var GameSetupState: typeof import("../js/gameSetupState");
declare var UiBuildMenu: typeof import("../js/uiBuildMenu");
declare var UiCardDetail: typeof import("../js/uiCardDetail");
declare var UiCardOrder: typeof import("../js/uiCardOrder");
declare var UiCardSelect: typeof import("../js/uiCardSelect");
declare var UiCardSelectEffects: typeof import("../js/uiCardSelectEffects");
declare var UiDiceChoice: typeof import("../js/uiDiceChoice");
declare var UiDiceDisplay: typeof import("../js/uiDiceDisplay");
declare var UiGameStatusView: typeof import("../js/uiGameStatusView");
declare var UiInputPolicy: typeof import("../js/uiInputPolicy");
declare var UiLogDisplay: typeof import("../js/uiLogDisplay");
declare var UiLogHighlightEffects: typeof import("../js/uiLogHighlightEffects");
declare var UiModalClose: typeof import("../js/uiModalClose");
declare var UiModalDomEffects: typeof import("../js/uiModalDomEffects");
declare var UiModalOpen: typeof import("../js/uiModalOpen");
declare var UiModalPolicy: typeof import("../js/uiModalPolicy");
declare var UiModalRuntime: typeof import("../js/uiModalRuntime");
declare var UiPendingEffects: typeof import("../js/uiPendingEffects");
declare var UiPendingMenu: typeof import("../js/uiPendingMenu");
declare var UiPlayerDisplay: typeof import("../js/uiPlayerDisplay");
declare var UiRenderRuntime: typeof import("../js/uiRenderRuntime");
declare var UiRuntimeSnapshot: typeof import("../js/uiRuntimeSnapshot");
declare var UiScreenFocus: typeof import("../js/uiScreenFocus");
declare var UiTabView: typeof import("../js/uiTabView");
declare var UiTabEffects: typeof import("../js/uiTabEffects");
declare var UiTurnAnnouncer: typeof import("../js/uiTurnAnnouncer");
declare var UiTurnPrivacy: typeof import("../js/uiTurnPrivacy");
declare var UiTutorial: typeof import("../js/uiTutorial");
declare var UiWinner: typeof import("../js/uiWinner");
declare var OnlineRuntimeState: typeof import("../js/onlineRuntimeState");

declare var beginOnlineCardSelection: (() => boolean) | undefined;
declare var checkAutoSkip: (() => void) | undefined;
declare var checkOnlineReadiness: (() => void) | undefined;
declare var clearOnlineSessionStorage: (() => void) | undefined;
declare var ensureCurrentScreenFocus: (() => void) | undefined;
declare var getEnabledCardSelection: (() => Set<string>) | undefined;
declare var getEnabledLandmarkSelection: (() => Set<string>) | undefined;
declare var isOnlineReconnectInputBlocked: (() => boolean) | undefined;
declare var markOnlineGameFinished: (() => void) | undefined;
declare var recordGameStats: ((winner: InstanceType<typeof import("../js/Player")>, game: InstanceType<typeof import("../js/GameManager")>, cpuPlayers: unknown[]) => void) | undefined;
declare var refreshPwaUpdateState: (() => void) | undefined;
declare var renderAdSlot: ((slot: string) => string) | undefined;
declare var renderStats: (() => void) | undefined;
declare var replaceEnabledCardSelection: ((values: string[]) => unknown) | undefined;
declare var replaceEnabledLandmarkSelection: ((values: string[]) => unknown) | undefined;
declare var replaceMarketRuleSelection: ((value: string) => unknown) | undefined;
declare var saveGameState: (() => void) | undefined;
declare var saveOnlineCardSelection: (() => boolean) | undefined;
declare var showCoinAnimation: ((playerIndex: number, diff: number) => void) | undefined;
declare var updateDiceDisplay: ((diceValues: number[]) => void) | undefined;
declare var safeStorageSet: ((key: string, value: unknown) => boolean) | undefined;
declare var safeStorageRemove: ((key: string) => void) | undefined;
declare var updateResumeButton: (() => void) | undefined;
declare var updateGameActivityStatus: (() => void) | undefined;
declare var showCrashScreen: ((error: unknown) => void) | undefined;
declare var notifyGameLifecycleFinish: ((winner: unknown) => void) | undefined;
declare var syncUiInteractabilityAfterRender: ((reason?: string) => void) | undefined;
declare var schedulePostBuildUiStabilizer: ((reason?: string) => void) | undefined;
declare var getOnlineActionFlightState: (() => { inFlight: boolean }) | undefined;
declare var onlineActionInFlight: boolean | undefined;
declare var onlineActionInFlightAt: number | undefined;
declare var markClientFlowCheckpoint: ((event: string, details?: Record<string, unknown>) => void) | undefined;
declare var reportClientError: ((input: unknown) => void) | undefined;
declare var SHOP_STOCK: Record<string, number>;
