// The online composition root is a classic script with explicit module adapters.
// Keep its runtime globals bound to the exported types of those adapters.
declare var ClientStorage: typeof import("../js/clientStorage");
declare var GameEngine: typeof import("../js/gameEngine");
declare var GameEngineClientShadow: typeof import("../js/gameEngineClientShadow");
declare var GameEngineRuntimeAdapter: typeof import("../js/gameEngineRuntimeAdapter");
declare var GameRuntimeState: typeof import("../js/gameRuntimeState");
declare var GameSchemaNegotiation: typeof import("../js/gameSchemaNegotiation");
declare var GameSchemaRecreateWire: typeof import("../js/gameSchemaRecreateWire");
declare var GameSchemaWire: typeof import("../js/gameSchemaWire");
declare var GameSelectionState: typeof import("../js/gameSelectionState");
declare var GameSetupState: typeof import("../js/gameSetupState");
declare var OnlineActionApplyFailure: typeof import("../js/onlineActionApplyFailure").OnlineActionApplyFailure;
declare var OnlineActionCommit: typeof import("../js/onlineActionCommit").OnlineActionCommit;
declare var OnlineActionGap: typeof import("../js/onlineActionGap").OnlineActionGap;
declare var OnlineActionLog: typeof import("../js/onlineActionLog").OnlineActionLog;
declare var OnlineActionNoGame: typeof import("../js/onlineActionNoGame").OnlineActionNoGame;
declare var OnlineActionSequence: typeof import("../js/onlineActionSequence").OnlineActionSequence;
declare var OnlineActionTimeout: typeof import("../js/onlineActionTimeout").OnlineActionTimeout;
declare var OnlineAppErrorRuntime: typeof import("../js/onlineAppErrorRuntime");
declare var OnlineClientEffects: typeof import("../js/onlineClientEffects");
declare var OnlineComposition: typeof import("../js/onlineComposition");
declare var OnlineDecodeFailure: typeof import("../js/onlineDecodeFailure").OnlineDecodeFailure;
declare var OnlineDiagnosticState: typeof import("../js/onlineDiagnosticState");
declare var OnlineDomEffects: typeof import("../js/onlineDomEffects");
declare var OnlineEffectAuthority: typeof import("../js/onlineEffectAuthority").OnlineEffectAuthority;
declare var OnlineGameInitializer: typeof import("../js/onlineGameInitializer");
declare var OnlineHostChanged: typeof import("../js/onlineHostChanged").OnlineHostChanged;
declare var OnlineHostlessRestoreState: typeof import("../js/onlineHostlessRestoreState");
declare var OnlineInboundActionRuntime: typeof import("../js/onlineInboundActionRuntime");
declare var OnlineLobbyRequestRuntime: typeof import("../js/onlineLobbyRequestRuntime");
declare var OnlineLobbyRequestState: typeof import("../js/onlineLobbyRequestState");
declare var OnlineLobbySelectionRuntime: typeof import("../js/onlineLobbySelectionRuntime");
declare var OnlineLobbyStartRuntime: typeof import("../js/onlineLobbyStartRuntime");
declare var OnlinePayload: typeof import("../js/onlinePayload").OnlinePayload;
declare var OnlinePendingOutboundState: typeof import("../js/onlinePendingOutboundState");
declare var OnlinePendingResend: typeof import("../js/onlinePendingResend").OnlinePendingResend;
declare var OnlinePlayerSettings: typeof import("../js/onlinePlayerSettings");
declare var OnlineReadiness: typeof import("../js/onlineReadiness").OnlineReadiness;
declare var OnlineReconnectCleanup: typeof import("../js/onlineReconnectCleanup").OnlineReconnectCleanup;
declare var OnlineReconnectRequest: typeof import("../js/onlineReconnectRequest").OnlineReconnectRequest;
declare var OnlineReconnectState: typeof import("../js/onlineReconnectState");
declare var OnlineRejoinActivationRuntime: typeof import("../js/onlineRejoinActivationRuntime");
declare var OnlineRejoinPersistence: typeof import("../js/onlineRejoinPersistence").OnlineRejoinPersistence;
declare var OnlineRejoinPreparationRuntime: typeof import("../js/onlineRejoinPreparationRuntime");
declare var OnlineRejoinRuntime: typeof import("../js/onlineRejoinRuntime");
declare var OnlineRestoreAbort: typeof import("../js/onlineRestoreAbort").OnlineRestoreAbort;
declare var OnlineRestoreActivation: typeof import("../js/onlineRestoreActivation").OnlineRestoreActivation;
declare var OnlineRestoreLifecycleState: typeof import("../js/onlineRestoreLifecycleState").OnlineRestoreLifecycleState;
declare var OnlineRestoreQueue: typeof import("../js/onlineRestoreQueue").OnlineRestoreQueue;
declare var OnlineRestoreQueueState: typeof import("../js/onlineRestoreQueueState").OnlineRestoreQueueState;
declare var OnlineRestoreRank: typeof import("../js/onlineRestoreRank").OnlineRestoreRank;
declare var OnlineRestoreReplay: typeof import("../js/onlineRestoreReplay").OnlineRestoreReplay;
declare var OnlineRestoreRequestRuntime: typeof import("../js/onlineRestoreRequestRuntime");
declare var OnlineRetryPolicy: typeof import("../js/onlineRetryPolicy");
declare var OnlineRoomShare: typeof import("../js/onlineRoomShare");
declare var OnlineRuntimeFlags: typeof import("../js/onlineRuntimeFlags");
declare var OnlineRuntimeState: typeof import("../js/onlineRuntimeState");
declare var OnlineSchemaTransport: typeof import("../js/onlineSchemaTransport");
declare var OnlineSessionLifecycle: typeof import("../js/onlineSessionLifecycle");
declare var OnlineSetupState: typeof import("../js/onlineSetupState");
declare var OnlineSocketConnect: typeof import("../js/onlineSocketConnect").OnlineSocketConnect;
declare var OnlineSocketDisconnect: typeof import("../js/onlineSocketDisconnect").OnlineSocketDisconnect;
declare var OnlineSocketEffects: typeof import("../js/onlineSocketEffects");
declare var RoomQrCode: typeof import("../js/roomQrCode");
declare var UiPlayerCount: typeof import("../js/uiPlayerCount");
declare var UiScreenFocus: typeof import("../js/uiScreenFocus");
declare var UiWinner: typeof import("../js/uiWinner");

declare var SHOP_STOCK: Record<string, number>;
declare var cancelAutoSkip: () => void;
declare var cancelDelayedHumanAction: () => void;
declare var createCpuPlayer: ((difficulty: string, options?: unknown) => CPU) | undefined;
declare var createOnlineStorageFacade: typeof import("../js/onlineStorage").createOnlineStorageFacade | undefined;
declare var invalidateCpuScheduleChain: () => void;
declare var isCurrentHumanUiTurn: (() => boolean) | undefined;
declare var io: (url?: string, options?: Record<string, unknown>) => import("socket.io-client").Socket;
declare var markClientFlowCheckpoint: ((event: string, details?: Record<string, unknown>) => void) | undefined;
declare var notifyGameLifecycleStart: (() => void) | undefined;
declare var readOnlineSession: (() => unknown) | undefined;
declare var refreshPwaUpdateState: (() => void) | undefined;
declare var render: (() => void) | undefined;
declare var replaceEnabledCardSelection: ((values: string[]) => unknown) | undefined;
declare var replaceEnabledLandmarkSelection: ((values: string[]) => unknown) | undefined;
declare var replaceMarketRuleSelection: ((value: string) => unknown) | undefined;
declare var reportClientError: ((error: unknown, details?: unknown) => void) | undefined;
declare var resetFullLog: (() => void) | undefined;
declare var resetStatsRecorded: (() => void) | undefined;
declare var resetUiLocksForGameReset: ((reason?: string) => void) | undefined;
declare var restoreUndoSnapshot: ((state: unknown) => boolean) | undefined;
declare var scheduleCPU: (() => void) | undefined;
declare var switchOnlineTab: ((tab: string) => void) | undefined;
declare var switchTab: ((tab: string) => void) | undefined;
declare var updateGameSelectionSummary: (() => string) | undefined;
declare var updateResumeButton: (() => void) | undefined;

interface Window {
    io: typeof io;
    MACHIKORO_CLIENT_VERSION?: string;
}

declare function cancelPendingLocalGameStart(): void;
